### PR TITLE
[#1527 #1529] Breaking change to the class renaming of `Kube` service discovery provider

### LINKED ISSUE #1527: Errors when running Ocelot.Provider.Kubernetes in Azure K8
## Expected Behavior / New Feature

Expect downstream routing to work

## Actual Behavior / Motivation for New Feature

404 error 

Error Code: UnableToFindServiceDiscoveryProviderError Message: Unable to find service discovery provider for type: consul errors found in ResponderMiddleware. Setting error response for request path:/products/g-ps4, request method: GET

## Steps to Reproduce the Problem

  1. routing file
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/home",
      "DownstreamScheme": "http",

      "UpstreamPathTemplate": "/test",
      "ServiceName": "productshttpaggegator",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/products/{postId}",
      "DownstreamScheme": "http",

      "UpstreamPathTemplate": "/products/{postId}",
      "ServiceName": "productshttpaggegator",
      "UpstreamHttpMethod": [ "Get" ]
    },

    "GlobalConfiguration",
    {
      "ServiceDiscoveryProvider": {
        "Namespace": "apigateway",
        "Type": "kube"
      }
    }
  ]
}
```
  2. API Gateway pod or service configured as LoadBalancer

## Specifications
  - Version:  Ocelot 17.0.0 and Ocelot.Provider.Kubernetes 17.0.0
  - Platform: Azure Kubernetes cluster
  - Subsystem: .NET 5 API project

### PR DESCRIPTION
**Pull request by ZisisTsatsas**
The `Type` field for the [Kubernetes](https://ocelot.readthedocs.io/en/latest/features/kubernetes.html) example is outdated in the docs

----

## Fixes #1527 #1529 
- #1527 
- #1529

### CODE REVIEW

**Comment by raman-m** [comment]
@ZisisTsatsas  Hi Zisis!
Thanks for the issue reporting!

You are right, the docs were not updated.
But it was my mistake when I renamed the class a half of the year ago... Seems we need to rename the class back to `Kube`.
So, finally there should be old two types: `Kube` and `PollKube`... and docs can be unchanged.
Sorry, for this breaking change!

@ggnaegi  Do you agree using old types `Kube` and `PollKube`? But I know you don't use these providers...

**Comment by raman-m** [comment]
@ZisisTsatsas  Could you help me with resolving this breaking change plz?
Or, I will work on the issue this weekend...

**Comment by raman-m** [comment]
The root cause of the problem:
https://github.com/ThreeMammals/Ocelot/blob/c9510b1c6aed7902e681978f5104bd2780f2f5dd/src/Ocelot/ServiceDiscovery/ServiceDiscoveryProviderFactory.cs#L59

of these block of code:
https://github.com/ThreeMammals/Ocelot/blob/c9510b1c6aed7902e681978f5104bd2780f2f5dd/src/Ocelot/ServiceDiscovery/ServiceDiscoveryProviderFactory.cs#L55-L63

where `_delegates is ServiceDiscoveryFinderDelegate` and it is added into the DI:
https://github.com/ThreeMammals/Ocelot/blob/c9510b1c6aed7902e681978f5104bd2780f2f5dd/src/Ocelot.Provider.Kubernetes/OcelotBuilderExtensions.cs#L11

Finally, in this line of code we have
https://github.com/ThreeMammals/Ocelot/blob/c9510b1c6aed7902e681978f5104bd2780f2f5dd/src/Ocelot/ServiceDiscovery/ServiceDiscoveryProviderFactory.cs#L59
&rarr; `if ("KubernetesServiceDiscoveryProvider".ToLower() == "Kube".ToLower())` **which is `false` always!**
This is the bug and the breaking change ❗

**Comment by raman-m** [comment]
Hi @ZisisTsatsas !
I found a couple of issues related to `Kube` provider and attached them to your PR 👉 
- #1527 
- #1529

So, these bugs will be closed officially 😉 

@ggnaegi  FYI

**Comment by raman-m** [comment]
@ggnaegi  Please review!

**Comment by raman-m** [comment]
Development **[completed](https://github.com/ThreeMammals/Ocelot/pull/1954#event-11765218263)** ✔️

**Review by ggnaegi — APPROVED** [review]

**Review by raman-m — APPROVED** [review]
[Approved](https://github.com/ThreeMammals/Ocelot/pull/1954#pullrequestreview-1874676561) by @ggnaegi 

The [build](https://circleci.com/gh/ThreeMammals/Ocelot/3265) is 🟢 

Ready for delivery! ✔️

**Comment by raman-m** [comment]
@ZisisTsatsas
Will you use our updated & fixed Kubernetes provider and Ocelot after the release? 😉

**Comment by ZisisTsatsas** [comment]
> @ZisisTsatsas Will you use our updated & fixed Kubernetes provider and Ocelot after the release? 😉

I will be using it! Thanks for the quick udpate

**Pull request merged**
