### PR TITLE
Fix catch all route on UpstreamTemplatePatternCreator regex to match …

### PR DESCRIPTION
**Pull request by marcoaam**
Fixes issue #407

### CODE REVIEW

**Comment by TomPallister** [comment]
@marcoaam there is a problem with one of the acceptance tests so we need to fix this before we merge the PR.

**Comment by marcoaam** [comment]
Sorry @TomPallister. I thought I did a full run but I must have missed that test. I will have a look.

**Comment by marcoaam** [comment]
@TomPallister I fixed the test but after looking at it more closely I decided to remove it as it doesn't seem to me a valid scenario. This route should not return a 404 as it is not any different from the other 2 tests in that file like "should_return_response_200_with_forward_slash_and_placeholder_only" and "should_return_response_200_with_nothing_and_placeholder_only" . 

I think a route with /somepath/{everything} should be fine to get called with just /somepath/ or /somepath. Feel free to let me know if this is not the case and I can revert that commit.  Let me know what you think and if this would cause any issues. Thanks

**Comment by marcoaam** [comment]
The other option could be get all of those 3 scenarios to return 404 as the placeholder is empty and to have specific routes for "/" and "/somepath/" separate from the catch all routes. But that probably means some breaking changes for some people as it will impact the current routes.

**Comment by TomPallister** [comment]
@marcoaam the test is valid so we need to put it back in. The user has a reroute set up /products/{id}. Requesting /products/ to the api should match not that route, a request on /products/1 should match.

The solution is to make the regex not match .* and only valid url characters until the next slash or end of string whichever comes first.

**Comment by marcoaam** [comment]
Thanks for getting back to me so quickly. No problem. I will get that done.

Maybe something for another time but I still think that maybe it is worth reviewing those 2 test scenarios that I mentioned as they are very similar to this scenario but they expect 200 instead of not found and that seems to me inconsistent with this current one.

**Comment by TomPallister** [comment]
@marcoaam looks good. I will merge and we can get it in the next release!

**Pull request merged**
