### PR TITLE
Added OpenTracing support with sample and tests.

### PR DESCRIPTION
**Pull request by kjellegafvelin**
Fix for #495 

## Proposed Changes

 Added support for the OpenTracing API so it is possible to use either Jaeger, Zipkin or any other tracing software with Ocelot.

### CODE REVIEW

**Comment by kjellegafvelin** [comment]
Seems like there were no interest in this.

**Comment by TomPallister** [comment]
@kjellegafvelin Ill try and get this merged today, sorry no one has looked at it :(

**Comment by kjellegafvelin** [comment]
No problem. But wait a while, I'm gonna test the Open Tracing .net package first.

**Comment by TomPallister** [comment]
Sorry I already merged it on another branch. I added some docs. If you find any problems just open another PR!

**Comment by TomPallister** [comment]
I reverted the commit you can see my proposed changes if you want to bring them into your branch https://github.com/ThreeMammals/Ocelot/pull/1244

**Comment by TomPallister** [comment]
Sorry I already merged this from my local, not sure why this didn't merge your PR -_-

**Pull request closed without merging**
