### PR TITLE
Upgrade Projects

### PR DESCRIPTION
**Pull request by thiagoloureiro**
Fixes / New Feature #

## Proposed Changes

  - Update Nuget Packages to the Latest Version
  - Upgrade projects to support .NET Core 2.2
  - Updates in Sample Projects with Latest Ocelot and .NET Core 2.2

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
Investigating why the unit tests failed

**Comment by WeihanLi** [comment]
Since update from 2.0 to 2.2, maybe use `Microsoft.AspNetCore.App` instead of `Microsoft.AspNetCore.All` is more suitable, refer to <https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#update-aspnet-core-21>

> We recommend migrating to the `Microsoft.AspNetCore.App` metapackage for 2.1 and later.

**Comment by thiagoloureiro** [comment]
@WeihanLi yeah, agreed with you, i'll take a look it was a lot of changes yesterday I made to this.

**Comment by WeihanLi** [comment]
@thiagoloureiro  Thanks for your effort, it seemed travis dotnet sdk should be updated also.

travis ci build use dotnet core sdk 2.1 for now

<https://github.com/ThreeMammals/Ocelot/blob/projects_upgrade/.travis.yml#L16>

image

**Comment by thiagoloureiro** [comment]
@WeihanLi ah! I see, I'll do more changes and will merge soon, most probably I will run a code cleanup, optimise usings and some other stuff before merge.

**Pull request merged**
