### PR TITLE
fix HttpRequesterMiddleware does not call next bug

### PR DESCRIPTION
**Pull request by WeihanLi**
call next so that we can do something with the response, such as add some custom header etc...

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
@WeihanLi Both of your PRs are failing on the tests, can't merge, can you check it please?

**Comment by WeihanLi** [comment]
I'm confused with the tests with the CI, could you please help me on fix the problem?

**Comment by thiagoloureiro** [comment]
@WeihanLi have you tried to run the tests locally? and see where it's breaking, it's easie

**Comment by WeihanLi** [comment]
I've tried locally, but nothing failed test found.

I've run the follows scripts in powershell:

- `.\build-and-run-tests.ps1`
- `.\run-acceptance-tests.ps1` 
- `.\run-unit-tests.ps1`

image

image

image

**Comment by thiagoloureiro** [comment]
@WeihanLi I will fork both of your repos and run the tests here to check,.

**Pull request merged**
