### PR TITLE
Support dynamic routing configuration in Service Fabric

### PR DESCRIPTION
**Pull request by RamjotSingh**
Fixes / New Feature #939 

## Proposed Changes
Adding a new extension of Ocelot for Service Fabric. More details are in the issue. The TL;DR version is that this extension allows you to change routing without touching Ocelot at all.

The routes are no longer put in Ocelot.json instead each service declares it's routes in their Service Manifest. This looks something like this

```xml
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="Web1Pkg"
                 Version="1.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <!-- This is the name of your ServiceType. 
         This name must match the string used in RegisterServiceType call in Program.cs. -->
    <StatelessServiceType ServiceTypeName="Web1Type">
      <Extensions>
        <Extension Name="Ocelot.Routing">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="ocelot.routing.template">/api/{value},/EquipmentInterfaces:/api2/testing</Label>
          </Labels>
        </Extension>
      </Extensions>
    </StatelessServiceType>
  </ServiceTypes>
```

Service fabric cluster services are probed every 30 seconds and routes are recalculated. If a change occurs, configuration change event is fired and Ocelot reloads the components and routing is changed.

I have tested on Windows only at the moment. I have completed testing on UnSecure cluster. Testing on Secure cluster.

### Sample usage
```cs
config
    .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
    .AddJsonFile("appsettings.json", true, true)
    .AddJsonFile("Ocelot.json")
    .AddServiceFabricExtension(new ServiceFabricClientFactoryOptions
    {
        ClusterManagementEndpoint = "http://localhost:19080"
    })
    .AddEnvironmentVariables();
```

### Pending
- [X] Windows UnSecure cluster
- [x] Windows Secure cluster
- [ ] Unit Tests

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
Plans for unit/integration tests and when we can have this done for merging? :)

**Comment by RamjotSingh** [comment]
@thiagoloureiro I first wanted to have your opinion on if you liked the design. If people are in general ok with the design I will start working on Unit tests.

**Comment by thiagoloureiro** [comment]
@RamjotSingh Oh, you're right mate. Give me some time to check this out then.
Thanks!

**Comment by RamjotSingh** [comment]
The reason I had changed namespace was coz the providers were proving ServiceDiscovery while this is providing RouteDiscovery. But if you feel they should be the same, I can change it. Do you want me to rename the assembly too?

P.S. I was thinking of having a Provider for SF at a later point which does not use SF's own ReverseProxy but directly reaches service instance. But that is still up in the air and I am not super sure it is a good idea. My idea was to name that assembly (and namespace) as Ocelot.Provider.ServiceFabric

**Comment by RamjotSingh** [comment]
@thiagoloureiro , @TomPallister Did you get a chance to look at this?

**Comment by RamjotSingh** [comment]
@thiagoloureiro , @TomPallister Can you please take a look.

**Comment by geffzhang** [comment]
> The reason I had changed namespace was coz the providers were providing ServiceDiscovery while this is providing RouteDiscovery. But if you feel they should be the same, I can change it. Do you want me to rename the assembly too?
> 
> P.S. I was thinking of having a Provider for SF at a later point which does not use SF's own ReverseProxy but directly reaches service instance. But that is still up in the air and I am not super sure it is a good idea. My idea was to name that assembly (and namespace) as Ocelot.Provider.ServiceFabric

ok

**Comment by RamjotSingh** [comment]
@thiagoloureiro Any thoughts?

**Comment by RamjotSingh** [comment]
@thiagoloureiro, @TomPallister Any plans for taking a look at this PR?

**Comment by TomPallister** [comment]
please open PR again against master branch

**Comment by raman-m** [comment]
@RamjotSingh @ggnaegi 
It is interesting! Would you like to reopen this PR?

**Pull request closed without merging**
