### PR TITLE
Feature/add style cop analyzers

### LINKED ISSUE #253: Static code analysis
Now we're getting a larger number of contributors it might be useful to enforce a few rules around code style. 

I use https://github.com/DotNetAnalyzers/StyleCopAnalyzers on most of my projects, which uses Roslyn analyzers to flag up violations at build time and, if you're using Visual Studio, when you're editing the code.

If we do implement this I want to avoid making it a painful experience for contributors... many of the rules are contentious, so I'd suggest that we start off with most rules turned off and then add in whatever we think will be useful to improve the code quality. 

Roslyn analyzers are not currently supported in vscode (though it looks like there is progress -
 see https://github.com/OmniSharp/omnisharp-vscode/issues/43) so anyone using vscode would only see the failures or warnings when building on the command line, which adds a lot of friction to the dev experience.

I've pushed up a work in progress which has most of the rules turned off - see https://github.com/binarymash/ocelot/tree/feature/AddStyleCopAnalyzers - and in the meantime, we can argue about whether `using` statements should be in alphabetical order ;)

### PR DESCRIPTION
**Pull request by binarymash**
Fixes #253

## Proposed Changes

Fix violations of these rules...

CS0105
CS0169
CS0414
CS0649
SA1025
SA1107
SA1216
SA1505
SA1507
SA1508
SA1509
SA1510
SA1512
SA1513
SA1515
SA1517
SA1518
SA1649

Pre-existing violations that I've not touched:

CS0618
CS1998

All other rules are either off or do not cause violations. 

Once this is merged in we can think about turning on other rules, if we want to.

### CODE REVIEW

**Comment by TomPallister** [comment]
@binarymash man you are a hero! I can't believe you gone through all the shit code I wrote and fixed it. I thought you were just gonna merge and then we would go rule by rule!!! Bloody hell.

I assume codes in PR match up to http://stylecop.soyuz5.com/StyleCop%20Rules.html

Ill go through them and make sure I understand everything then merge.

**Comment by TomPallister** [comment]
Dont worry about CS0618 thats for me to sort at some point..

CS1998 really annoys me because you have an async API but some implementations are not async. If you wrap it with a task you are spinning up a task for no reason..is there a better way with this?

**Comment by TomPallister** [comment]
If you want me to fix the merge conflicts let me know. You have already done loads and I really appreciate it!!

**Comment by binarymash** [comment]
Not sure about the CS1998 as I didn't really look into them. If it's not async then can you just you `Task.FromResult(...)`?

Actually, forgot to say before, there's still a couple of violations for CS0649 (variables which are being used but never assigned to). These are both in test code - not sure if the tests are incorrect, or what. Any ideas?

**Comment by TomPallister** [comment]
I'd imagine the CS0649 in the tests are being used in constructors or something but they get passed somewhere else...there is quite a lot of data in transit in the whole project.

**Comment by TomPallister** [comment]
@binarymash you happy to merge this?

**Comment by binarymash** [comment]
yep.

**Comment by TomPallister** [comment]
let the arguments begin :)

**Pull request merged**
