### PR TITLE
Typo in loadbalancer.rst

### PR DESCRIPTION
**Pull request by ks1990cn**
Resolving spelling error, no new feature is introduced

## Proposed Changes
Document update for spelling

### CODE REVIEW

**Comment by raman-m** [comment]
Hi Tanmay!
Thanks for pointing to the typo! ✋ 
Regarding the word `algorythm`... Who knows, maybe it is an ancient British word. We need to ask Tom...🤣 

Usually [micro PRs cannot be considered](1678) as a real features or bugfixes...
You need to:
- find other typos in docs, a lot of typos
- choose open issue, assign, work on it, make a PR and additionally you can fix this typo 😉 

Which way do you prefer to go?

**Comment by ks1990cn** [comment]
Closing this PR, cause this is micro PR, will do with above methods. Thanks Raman

**Comment by raman-m** [comment]
😂

**Comment by ks1990cn** [comment]
haha! I wanted this as my first PR but still need to find different way @raman-m

**Comment by raman-m** [comment]
Issue has fixed in main, and released: [loadbalancer.rst](https://github.com/ThreeMammals/Ocelot/blob/main/docs/features/loadbalancer.rst?plain=1#L9)

**Pull request closed without merging**
