### PR TITLE
#692 Simplify downstream service config

### LINKED ISSUE #692: Question: DownstreamHostAndPorts alias
My team and I are test-driving Ocelot for a new project. We are wondering if it is possible to alias the `DownstreamHostAndPorts` somehow without having to repeat it for many endpoints. This is especially important to us when we think about overriding host and port per environment.

For example, for development purposes, we want to have Host and Port set to localhost and 5005, but for staging and production to a different host name and port. I understand that this is possible to do via override, but we'd rather not duplicate the entire definition again.

We'd like to define multiple hosts and ports in the global configuration and reference them in the downstream host and ports section.

Example: 
```
"GlobalConfiguration": {
  "BaseUrl": "https://our-system.net/api",
  "RequestIdKey": "X-Request-Id",
  "HostAndPorts": [
    {
      "Alias": "ServiceA",
      "Host": "localhost",
      "Port": "5005"
    }
  ]
}
```

Then, in the "ReRoutes" config, we'd use it instead of the host definition:
```
{
  "ReRoutes": [
    // other config
    "DownstreamHostAndPorts": [
      {
        "UseAlias": "ServiceA"
      }
    ]
  ]
}
```

Is this a use case you have come across? I guess, as a workaround, we could define host names in the hosts file of the system, but that requires all devs to have the same entries.

## Specifications
  - Version: 12.0.1
  - Platform: dotnet core 2.1.5

### PR DESCRIPTION
**Pull request by cezarypiatek**
## Closes #692
This allows to simplify downstream configuration by defining a given downstream service once in the global configuration and reuse it later by referencing with `GlobalHostKey`.

```json
{
  "Routes": [{
      "DownstreamPathTemplate": "/api/products/{productId}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "GlobalHostKey": "JsonPlaceholderService"
        }
      ],
      "UpstreamPathTemplate": "/products/{productId}",
      "UpstreamHttpMethod": [ "Put" ],
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      },
      "FileCacheOptions": { "TtlSeconds": 15 }
    },
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "GlobalHostKey": "JsonPlaceholderService"
        }
      ],
      "UpstreamPathTemplate": "/posts/",
      "UpstreamHttpMethod": [ "Get" ],
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      },
      "FileCacheOptions": { "TtlSeconds": 15 }
    },
    {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "www.bbc.co.uk",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/bbc/",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],

  "GlobalConfiguration": {
    "RequestIdKey": "ot-traceid",
    "DownstreamHosts": {
      "JsonPlaceholderService": {
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }
    } 
  }
}
```

This also allows to very easily override downstream address per environment.

**Important**: I've changed a lot of files because I need to rename `FileHostAndPort` &rarr; `FileDownstreamHostConfig`.
All things related to rename are in a separated commit.

### CODE REVIEW

**Comment by Bonsai12345** [comment]
I can't believe this is not possible already. The docu says "The Global configuration is a bit hacky and allows overrides of Route specific settings." That sounds like it's exactly for this purpose. Is there a workaround for this prior to this change?

**Comment by cezarypiatek** [comment]
I didn't find anything that could allow for that. The Global Settings seems to be quite limited

**Comment by Bonsai12345** [comment]
> I didn't find anything that could allow for that. The Global Settings seems to be quite limited

Me neither sadly, this would be very useful.

**Comment by gao-artur** [comment]
https://github.com/ThreeMammals/Ocelot/issues/692#issuecomment-730880491

**Comment by raman-m** [comment]
@cezarypiatek Hi Cezary!
Thanks for your interest in Ocelot!
Your PR is just great!

Unfortunately a lot of thing have changed during 3 years, and your feature branch contains merge conflicts which are impossible to resolve.

Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, new **develop** branch will occur with all top commits!
After that, create new feature branch from **develop** one, and cherry pick required commits from current branch.

Syncing fork will ask you to resolve merge conflicts of this branch.
Give a try!

**Comment by raman-m** [comment]
@mariotacke Hi Mario!
As an author of the #692 issue,
Could you review the current solution please?

---

@NicoJuicy @philproctor @gao-artur @golavr
After your discussions of the issue #692 , could you join to code review sessions too?

**Review by RaynaldM — APPROVED** [review]

**Comment by NicoJuicy** [comment]
First PR review on Ocelot, but PR looks good.

Just an addition, the current assumption is that the key is defined within the same GlobalConfiguration file.

I think functionality-wise, it would simplify a lot if you could reference a setting in app.settings. Instead of referencing a named host in the same ocelot config. 

Eg. Current: JsonPlaceholderService
Alternative: '/ProxySettings/FeatureFlagManagerEndpoint'

This setting would be looked up in:
appsettings.json
{
 "ProxySettings":{ "FeatureFlagManagerEndpoint":"https://myfeatureflagmanager.domain.com"}
}

This however would expect a URL, instead of the combined host + port that seems to be standard within Ocelot.

**Review by NicoJuicy — COMMENTED** [review]
First PR review on Ocelot, but PR looks good.

Just an addition, the current assumption is that the key is defined within the same GlobalConfiguration file.

I think functionality-wise, it would simplify a lot if you could reference a setting in app.settings. Instead of referencing a named host in the same ocelot config.

Eg. Current: JsonPlaceholderService
Alternative: '/ProxySettings/FeatureFlagManagerEndpoint'

This setting would be looked up in:
appsettings.json
{
"ProxySettings":{ "FeatureFlagManagerEndpoint":"[https://myfeatureflagmanager.domain.com"}](https://myfeatureflagmanager.domain.com%22%7D/)
}

This however would expect a URL, instead of the combined host + port that seems to be standard within Ocelot.

**Comment by raman-m** [comment]
@NicoJuicy reviewed [on Aug 11](#pullrequestreview-1573341476):
> I think functionality-wise, **it would simplify a lot if you could reference a setting in app.settings.** Instead of referencing a named host in the same ocelot config.

Nico,
Thanks for your review!
Your idea is good! We have [some problems with configuration JSON](../issues?q=is%3Aissue+is%3Aopen+merging).
There are a lot of feature requests which would like to change [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html) feature: 👇 
- #1183 
- #1227 

So, your idea to use **appsettings.json** for custom properties will allow to make the pipeline extendable and more stable.
Current **ocelot.json** design is a source of problems.  This [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html) feature was designed by Tom. 😄 
I believe migration to **appsettings.json** will solve a long list of issues, but such kind of refactoring requires a large efforts.

**Comment by NicoJuicy** [comment]
@raman-m I actually like the configuration how it is.
I have separate files per feature ( products, clients, 
.. ) the only thing that is annoying is that I have to repeat my endpoints ( I use it as a gateway for a pwa on top of a modular monolith)

The ocelot implementation in the same app avoids cors issues.

Screenshot_20230818_143710_Chrome
Screenshot_20230818_143710_Chrome

**Review by raman-m — CHANGES_REQUESTED** [review]
@cezarypiatek
Hi Cezary!
We should keep in mind that class renaming is quite aggressive refactoring, and we must avoid such refactoring in favor of using composition and inheritance.

**Comment by raman-m** [comment]
> @NicoJuicy commented [on Aug 18](#issuecomment-1683858724)

Bad formatting of the description! It is hard to read!
I guess we must discuss the PR but not your custom solutions. You could open any issues in backlog to other custom features.

**Comment by raman-m** [comment]
@cezarypiatek commented [on Oct 13, 2020](#issue-720657678):
> **Important**: I've changed a lot of files because I need to rename `FileHostAndPort` &rarr; `FileDownstreamHostConfig`.
All things related to rename are in a separated commit.

Yeah, it is bad idea! See code review plz!
We should not rename classes, and should not provide any breaking changes at all!

---
> This also allows to very easily override downstream address per environment.

What Ocelot feature should we use to achieve this? 😉 

---

> This allows to simplify downstream configuration by defining a given downstream service once in the global configuration and reuse it later by referencing with `GlobalHostKey`.
>```json
> {
>   "Routes": [{
>       "DownstreamPathTemplate": "/api/products/{productId}",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "GlobalHostKey": "JsonPlaceholderService"
>         }
>       ],
>       "UpstreamPathTemplate": "/products/{productId}",
>       "UpstreamHttpMethod": [ "Put" ],
>     },
>     {
>       "DownstreamPathTemplate": "/posts",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "GlobalHostKey": "JsonPlaceholderService"
>         }
>       ],
>       "UpstreamPathTemplate": "/posts/",
>       "UpstreamHttpMethod": [ "Get" ],
>     },
>     {
>       "DownstreamPathTemplate": "/",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "Host": "www.bbc.co.uk",
>           "Port": 80
>         }
>       ],
>       "UpstreamPathTemplate": "/bbc/",
>       "UpstreamHttpMethod": [ "Get" ]
>     }
>   ],
> 
>   "GlobalConfiguration": {
>     "RequestIdKey": "ot-traceid",
>     "DownstreamHosts": {
>       "JsonPlaceholderService": {
>         "Host": "jsonplaceholder.typicode.com",
>         "Port": 80
>       }
>     } 
>   }
> }
> ``` 

More short version:
```json
{
  "Routes": [{
      "DownstreamHostAndPorts": [
        {
          "GlobalHostKey": "JsonPlaceholderService"
        }
      ],
    },
  ],

  "GlobalConfiguration": {
   "DownstreamHosts": {
      "JsonPlaceholderService": {
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }
    } 
  }
}
``` 

What is simplified here? You just removed one line from the "**DownstreamHostAndPorts**" property...
I understand simplification like that:
```json
{
  "Routes": [{
      "DownstreamHostAndPorts": ["JsonPlaceholderService"],
    },
  ],

  "GlobalConfiguration": {
   "DownstreamHosts": {
      "JsonPlaceholderService": {
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }
    } 
  }
}
``` 
...which looks more simplified.

But, because "DownstreamHostAndPorts" property has described in [a lot of docs](https://ocelot.readthedocs.io/en/latest/features/routing.html), it is totally crazy idea to refactor this property by introducing breaking changes and confusion in docs!
It seems we have to design a new property for route to achieve real simplification.
```json
{
  "Routes": [{
      "DownstreamHosts": ["JsonPlaceholderService"],
    },
  ],
  "GlobalConfiguration": {
   "DownstreamHosts": {
      "JsonPlaceholderService": {
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }}}
}
``` 

Moreover, I suggest you to introduce Scheme property in alias-object:
```json
{
  "Routes": [
    // old definition
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "jsonplaceholder.typicode.com",
          "Port": 80
        }
      ],
    },

    // new definition 1
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHosts": ["JsonPlaceholderService"],
    },

    // new definition 2
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamAlias": "JsonPlaceholderService", // not array!!!
    },
  ],

  "GlobalConfiguration": {
   "DownstreamHosts": {
      "JsonPlaceholderService": {
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }},
   "DownstreamAliases": {
      "JsonPlaceholderService": {
        "Scheme": "http",
        "Host": "jsonplaceholder.typicode.com",
        "Port": 80
      }}
  }
}
``` 
Pay attention "DownstreamAlias" of a route can be just single string, not an array object.
@cezarypiatek Looks simplistic?
@mariotacke Looks good?

---

**Finally,** because "DownstreamAliases" contains all required props of an URL, we can define alias like that:
```json
{
  "Routes": [
    // old definition
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "jsonplaceholder.typicode.com",
          "Port": 80
        }
      ],
    },

    // new definition
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamUrl": "JsonPlaceholderService", // not array!!!
    },
  ],

  "GlobalConfiguration": {
   "DownstreamUrls": {
      "JsonPlaceholderService": "http://jsonplaceholder.typicode.com",
    }
  }
}
``` 
But it seems such simplification by aliases is overhead design, because route can have simplest URL definition:
```json
{
  "Routes": [
    // old definition
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "jsonplaceholder.typicode.com",
          "Port": 80
        }
      ],
    },

    // new definition
    {
      "DownstreamPathTemplate": "/posts",
      "DownstreamUrl": "http://jsonplaceholder.typicode.com",
      // and/or
      "Downstream": "http://jsonplaceholder.typicode.com",
    },
  ],

  "GlobalConfiguration": {
    // empty
  }
}
``` 
No global aliases at all. And global config is empty. And we use default port `80` of the scheme!

**Comment by ggnaegi** [comment]
@raman-m 
``` 
{
      "DownstreamPathTemplate": "/posts",
      "DownstreamScheme": "http",
      "DownstreamHosts": ["JsonPlaceholderService"],
    },
```

This is an interesting PR, separating Routes and Hosts is a wise choice... We could imagine splitting the config file and with the help of an IHostedService retrieve the clusters dynamically. Then we would achieve a real polling 😄

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 4](#issuecomment-1746310184)

Gui, I don't know... This PR is about placeholders in global section, and this PR is not about dynamic routing, or service discovery...
To be fair, it will be hard to work on this PR...
It seems, as an author, @cezarypiatek doesn't care about his PR anymore. 😢 I've asked him a lot of questions, but he doesn't care...

**Comment by cezarypiatek** [comment]
> > @ggnaegi commented [on Oct 4](#issuecomment-1746310184)
> 
> Gui, I don't know... This PR is about placeholders in global section, and this PR is not about dynamic routing, or service discovery... To be fair, it will be hard to work on this PR... It seems, as an author, @cezarypiatek doesn't care about his PR anymore. 😢 I've asked him a lot of questions, but he doesn't care... I cannot develop ideas of other developers when they don't respond, don't write code...

Correct, I don't care. I needed that 3 years ago.

**Comment by ggnaegi** [comment]
@raman-m It's still a very interesting PR though. A "neat" but breaking solution would be to use the ``` ServiceName ``` we would use for consul or eureka and then allow the host definition in GlobalConfiguration.

**Comment by raman-m** [comment]
> @cezarypiatek commented [on Oct 7](#issuecomment-1751668815)

Strange answer... Good luck!

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 7](#issuecomment-1751959843)

Let's decide what to do with this PR after October's release...

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 8, 2023](https://github.com/ThreeMammals/Ocelot/pull/1353#issuecomment-1751959843)

Each new release seems to bring more conflicts our way! 😂

**Comment by raman-m** [comment]
This PR cannot be accepted for the following reasons:
- There is an enormous number of merge conflicts.
- The author has [expressed no intention](https://github.com/ThreeMammals/Ocelot/pull/1353#issuecomment-1751668815) to deliver this feature.
- The quality of the PR is poor.
- The proposed changes are in draft status: a single class renaming has resulted in an enormous number of changed files.

The PR will be closed.

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 4, 2023](https://github.com/ThreeMammals/Ocelot/pull/1353#issuecomment-1746310184)

The concept is commendable; however, as an OSS project, Ocelot project consistently faces challenges with professional contributions. While many developers propose ideas, only a handful are capable of implementing the feature.
I am open to someone else taking over this task. Are you ready?

**Comment by raman-m** [comment]
> @NicoJuicy commented [on Aug 18, 2023](https://github.com/ThreeMammals/Ocelot/pull/1353#issuecomment-1683858724)

Hello Nico,
I'm quite impressed with your concept of using alias-placeholders in the Host property, as it aligns well with the original concept of host aliases in #692. 😍
Just so you know, this PR will not be pursued further.
I would like to invite you to take on #692 officially. **Would you have the time and interest to contribute?**

**Pull request closed without merging**
