### PR TITLE
One less warning with async

### PR DESCRIPTION
**Pull request by AnthonySteele**
Fixes / New Feature #

## Proposed Changes

Remove a warning about the use of `async` without `await`: 

```
Warning	CS1998	
This async method lacks 'await' operators and will run synchronously. 
Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	
Ocelot.AcceptanceTests	C:\code\Ocelot\test\Ocelot.AcceptanceTests\ResponseCodeTests.cs	59	
```

### CODE REVIEW

**Comment by AnthonySteele** [comment]
I can look at more warnings to get familiar with the code, but I thought it best to start small.

Some of them should probably be suppressed, e.g.  `IDE1006`  in the tests

**Comment by raman-m** [comment]
Anthony,
A lot of warning and compiler messages were fixed by my PR #1663 .

After merging **develop** branch with conflicts resolution, I took [changes from develop branch](../blame/develop/test/Ocelot.AcceptanceTests/ResponseCodeTests.cs#L59) because `async` was removed. We create PRs to develop now.
And now I don't see changes in [diff](1208/files) at all.
Do you see? 😄 

I believe this warning is gone now.
Could you confirm that please?

**Comment by raman-m** [comment]
LoL 🤣 
You've closed the PR!

**Comment by AnthonySteele** [comment]
Yeah, it doesn't seem relevant any more (3 years ago?)

If we want to do this, it would be easier to start again. I don't have context after that time.

**Pull request closed without merging**
