### PR TITLE
Activate ChangeToken when Ocelot's configuration changes

### PR DESCRIPTION
**Pull request by ChrisSwinchatt**
New Feature #1036 

## Proposed Changes

  - Activate a change token when Ocelot's configuration changes

### CODE REVIEW

**Comment by TomPallister** [comment]
@ChrisSwinchatt looks good, would it be possible to get an acceptance or integration test showing this working end to end in Ocelot?

**Comment by ChrisSwinchatt** [comment]
Hi @TomPallister - Sorry for the late response, been very busy. I will write some more tests and look into updating documentation.

**Comment by ChrisSwinchatt** [comment]
I've added the tests & documentation changes. Not sure if I can do anything about the failing CI checks, all the tests pass at least.

**Comment by TomPallister** [comment]
I created another branch to kick off the CI and have merged it so closing this PR. Thanks for the contribution!

**Pull request closed without merging**
