### PR TITLE
Upstream header routing

### PR DESCRIPTION
**Pull request by mrclayman**
# Fixes / New Feature

Addition of support for request re-routing based also on upstream header configuration as per issues #360 and #624 

## Proposed Changes

  - Implementation of support for re-routing based on request's header configuration
  - Update of relevant tests to cover the new functionality
  - Update of relevant documentation to make clear how to make use of the new functionality

Downstream URL placeholder replacement mentioned in issue #360 is not yet supported although I do have plans to add support for that as well.

### CODE REVIEW

**Comment by TomPallister** [comment]
please open PR again against master branch

**Comment by raman-m** [comment]
@mrclayman 
What's the new PR number?
Let's link both of them.

**Comment by raman-m** [comment]
As a compromise we can retarget current PR still to develop, because develop branch is protected now and it is default branch of the repo! And, master branch was default one in 2020, I suppose.
So, just reopening this PR is required. 🤣

**Comment by mrclayman** [comment]
Just tried rebasing my branch on the current state in develop and yeah, I might as well scrap the current branch and start a new one since some of the basic components I used in the past are gone now. It makes perfect sense anyway since so much must have changed in the meantime.

**Comment by raman-m** [comment]
@mrclayman commented [on July 19](../issues/360#issuecomment-1642662698):
>Hm, for some reason, many of the changed files are coming up as "rewritten" even though I really only just added the bits I had implemented in the old branch, dammit.
>
>Let me know if that is a problem. :confused: Right now I feel like redoing everything. Those diffs are pretty much useless.

Are you saying about this commit: https://github.com/mrclayman/Ocelot/commit/022e81748d64624db4831b8281b69c27ac8bc3fa ?
Or about this PR?

Anyway you cannot use diff of this PR because the feature branch is very old! Don't even try to cherry pick because you will get multiple merge conflicts! Just apply ideas and changes manually in Visual Studio.
You have to create new feature branch from updated [develop](/mrclayman/Ocelot/tree/develop) one.

I see you've already updated [develop](/mrclayman/Ocelot/tree/develop) branch by merging [PR 1](/mrclayman/Ocelot/pull/1). But I forgot to ask to use Rebase option button. Sorry! It is always better to use fast-forwarding instead of merge commits.
And now **develop** branch is [1 commit ahead](/mrclayman/Ocelot/compare/ThreeMammals:Ocelot:develop...develop) of ThreeMammals:develop.
Let's remove this redundant merge commit and pull top commits once again, please!
Use [these instructions](1312#issuecomment-1640008692) plz I've provided for J.Lukawska. 

After fixing and updating your **develop** branch, you will be able to create new feature branch.
Let me know updating results please!

**Comment by raman-m** [comment]
And you will wonder more because you've created feature branch from [develop](/mrclayman/Ocelot/tree/develop) branch which is in invalid state!

Develop should be synced to head repo develop always, and it should have zero diff! It is important!
Use [these instructions](1312#issuecomment-1640008692) plz to recover your develop!

**Comment by mrclayman** [comment]
I guess that is my exit cue, Raman. I don't see the reason to continue working on this since, as you have stated, there is already another PR in the pipeline ready to be merged soon. I haven't seen @jlukawska 's changes but if they are otherwise okay, trying to keep my version alive is a waste of effort as far as I can tell.

**Comment by raman-m** [comment]
🆗 As you wish...
Hope for your future contributions to Ocelot!

P.S. Could you at least to use [these instructions](1312#issuecomment-1640008692) please to recover your develop?

**Comment by mrclayman** [comment]
Fair enough, I guess. Do you want me to drop the topmost merge commit on my develop branch and the rebase the latest from origin on top of that? I am not entirely sure I understand the goal of those instructions.

**Comment by raman-m** [comment]
@mrclayman commented [on July 24](#issuecomment-1648389531):
> Fair enough, I guess. Do you want me to drop the topmost merge commit on my develop branch and the rebase the latest from origin on top of that? I am not entirely sure I understand the goal of those instructions.

With pleasure!
The manipulation with protected branch requires having the write permission (you have only as repo owner).
If you will [add me as collaborator](/mrclayman/Ocelot/settings/access) of your repo, I will try to fix manually.

The problem is that I have to push changes forcibly to develop to remove redundant merge commit.
As repo owner you can make force push operation always. But not me.

If you don't want to give me [Collaborator role](/mrclayman/Ocelot/settings/access) then you can just remove develop branch from GitHub and [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, new **develop** branch will occur with all top commits!

**Comment by raman-m** [comment]
First of all disable protected branch policy for develop branch please!
After that maybe I will be able to fix the repo.

But it's better to add me as collaborator.

**Comment by mrclayman** [comment]
Just did that. :+1:

**Comment by raman-m** [comment]
image

Congrats! 🥳  Your develop branch is canonic now (has zero diff with upstream)!
Updated!

**Comment by raman-m** [comment]
Will do the rebasing tomorrow! Too late today!

Do you ask to rebase https://github.com/mrclayman/Ocelot/tree/upstream-header-routing branch?

**Comment by mrclayman** [comment]
Thanks for the assist. :+1: I've put all of my changes into the `upstream-header-routing-2023` branch after adapting them from the old branch this PR was based on.

**Comment by mrclayman** [comment]
What I did was create a new branch based on the current state of `develop` and just went over the changes I made in the old branch, picked them out and adapted for the new `develop`. I did not copy any files. I don't really understand why the diffs turned out like this, to be honest. Like I said earlier, I am just tempted to re-do everything from scratch.

**Comment by mrclayman** [comment]
I think the issue is the line endings. I mostly work in Linux and use system-dependent line ending setting in Rider. I'll see if switching to Windows-style LE solves this problem.

**Comment by raman-m** [comment]
Absolutely right!
This is line endings problem!

In develop branch line endings settings are:

image

---

In feature branch the settings are:

image

So, it seems you've overridden Line Endings settings somehow, probably manually...
Or, your `.gitattributes` differs from repository settings, or...

Don't do that now and in future!
You have to use common solution settings: [.editorconfig](../blob/develop/.editorconfig)

I have a lack of management rights to provide complete git setup for this problem.
It seems the easiest way to fix that, you have to create new feature branch and ensure you use repo settings, and provide changes manually.

Other approaches like `.editorconfig` or `.gitattributes` or `git add --renormalize` will not help because files of the repo, most of them have MIXED state of line endings. 😢 
This is the huge problem of repository now! So, I have to open issue in backlog now...

**Comment by mrclayman** [comment]
Well, actually your .editorconfig enforces LF endings, which is what Rider respects and then enforces on save. Seems like 
VS or some other editor doesn't care about .editorconfig. Not sure how I wound up with CRLF endings, but it seems that for now, I am going to disable LF line ending enforcement to make Rider keep whatever is in the files. :confused:

**Comment by mrclayman** [comment]
Okay, I have created a brand new PR #1684 . Take a look at it and let me know. I am wondering about the support for placeholders that some people voiced their interest in us supporting. I might look into it if it's still worth the hassle.

**Comment by raman-m** [comment]
Duplicate of #1684

**Pull request closed without merging**
