### PR TITLE
Fix typo in the name of the `DistributedCacheRateLimitCounterHandler` class

### PR DESCRIPTION
**Pull request by williamscs**
## Proposed Changes

This fixes a typo in a class name.

### CODE REVIEW

**Comment by raman-m** [comment]
LoL 🤣 Thank you, Chris, for your eagle eye! 🦅

**Comment by raman-m** [comment]
Have you ever heard about obfuscation technology? 😉  😆

**Comment by raman-m** [comment]
I can't get it... Why are there no references in DI? The class is defined, but not used in the solution... 🤯 
Seems this is very old Tom's idea, and not finished feature...

**Review by raman-m — APPROVED** [review]

**Comment by williamscs** [comment]
> I can't get it... Why are there no references in DI? The class is defined, but [not used in the solution](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+DistributedCacheRateLimitCounterHanlder&type=code)... 🤯 Seems this is very old Tom's idea, and not finished feature...

I only found it because of this issue: https://github.com/ThreeMammals/Ocelot/issues/609

I believe the intent is that it isn't used within the repo (though maybe it needs tests). I think you're supposed to instantiate yourself it in order to support rate limiting across multiple replicas. I was going to test it out this week or next.

**Comment by raman-m** [comment]
OK Do you use Redis Cache or something else?

**Pull request merged**
