### PR TITLE
Fix/issue666

### PR DESCRIPTION
**Pull request by aliprogrammer69**
fixed issue 
https://github.com/ThreeMammals/Ocelot/issues/666

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
@aliprogrammer69  Hi mate, your PR looks good, Just wondering if we need to unit test this method:

**GenerateRequestCacheKey**

**Comment by aliprogrammer69** [comment]
dear @thiagoloureiro  I wrote unit test to cover method  **GenerateRequestCacheKey** and sent pull request  AppVeyor build succeeded  but the travis ci returned error below
**The command "sudo apt-get install -qq dotnet-sdk-2.1=2.1.500*" failed and exited with 100 during .**

**Comment by thiagoloureiro** [comment]
> dear @thiagoloureiro I wrote unit test to cover method **GenerateRequestCacheKey** and sent pull request AppVeyor build succeeded but the travis ci returned error below
> 
> `The command "sudo apt-get install -qq dotnet-sdk-2.1=2.1.500*" failed and exited with 100 during .`

Sometimes travis-ci causes issues, appveyor was ok, so no worries.

**Comment by aliprogrammer69** [comment]
is there any problem? when are you going to release new version and publish to nuget?

**Comment by epcpu** [comment]
this bug costs a lot for us. 
thanks for your work on its fixing. 
when does it going to be released? is it possible to use it in following days?

**Comment by thiagoloureiro** [comment]
will release today later the new version ok ! :)

**Comment by raman-m** [comment]
@aliprogrammer69  Your design is ugly!

**Comment by raman-m** [comment]
@thiagoloureiro  You managed Ocelot project in 2019...
After closing and merging this PR the original feature #666  was not closed. Why?
Why didn't you close the feature?

**Pull request merged**
