### PR TITLE
Fixing Typo

### PR DESCRIPTION
**Pull request by anthonyliriano**
The correct spelling is Authorization

Fixes / New Feature #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
This isn't a typo, in UK english authorisation is correct, am I right ?

**Comment by margaale** [comment]
@thiagoloureiro you are right, but what spelling are we using in the rest of the documentation?
@AbolfazlRajabpour why would you approve a typo fix when you told me that english is not your language?

**Comment by thiagoloureiro** [comment]
@margaale  @tom is from UK, most probably he is using UK english into docs.

**Comment by AbolfazlRajabpour** [comment]
> @AbolfazlRajabpour why would you approve a typo fix when you told me that english is not your language?
Typically, documents are written in US English not UK. and this is a misspelling

**Comment by margaale** [comment]
So, if you can tell that you can write the documentation that I asked for...

**Pull request closed without merging**
