### PR TITLE
Add Ocelot.Common Project to the solution

### PR DESCRIPTION
**Pull request by ggnaegi**
New Feature #

It would be great to have a common project, addressing crosscutting concerns (standardized exceptions, string constants etc, maybe some factories...).

## Proposed Changes

 Create a new Ocelot.Common project
 Add Constants, eg. "ServiceFabric" to a static class, "Constants"

### CODE REVIEW

**Comment by ggnaegi** [comment]
@raman-m well, so I forgot to switch back to the develop branch...

**Comment by raman-m** [comment]
Well... I have a mixed feelings regarding this PR...

It seems you are trying to propose some new feature right in the PR. It doesn't, and it should not work.
You need to create an issue first and start discussions for acceptance.

Regarding this PR...
You are trying to show some idea with common project based on the code from develop. But you would like to improve the code from #1670 , right? I see a lot of code from the #1670  PR!
In this case you have to branch from [bug/polling-consul](https://github.com/ggnaegi/Ocelot/commits/bug/polling-consul) branch. And prepare new changes to merge to **bug/polling-consul**! That's how to see your new proposed changes.
Finally, if #1670  will be merged you will be able to re-target to the develop branch.
Do you see?

Sorry, I'm going to make this PR as draft...
I don't understand your idea right now.

**Comment by raman-m** [comment]
> [line endings](https://github.com/ThreeMammals/Ocelot/pull/1671/commits/ad3959927630ca52fe8f2e4474e99b94017bad14)

And do not change any line endings at all please! 
Such changes have just zero outcome!

Make new PR in your forked repo plz, and I will review it if you wish.

**Comment by ggnaegi** [comment]
@raman-m Yes, I made a mistake there. But, there is a reason why. For me, using string litterals for comparison is a code smell. I have several examples like, "ServiceFabric" and others. I will make a proposal, you're right.

**Comment by raman-m** [comment]
A soon as you've created new PR in your forked repo, then link both of PRs please: this PR to the new one.
Thank you!

**Pull request closed without merging**
