### PR TITLE
#1708 Generic polling mechanism for service discovery

### LINKED ISSUE #1708: Generic polling mechanism for discovery services (Consul, Eureka...)
## Expected Behavior / New Feature
The polling of discovery services is not specific to one type of discovery service. Therefore, polling management should not be specific to a service but generic.

So here we want to propose:

- A service manager that manages the list of microservice types (clusters)
- An instance manager that manages the list of possible destinations

Obtaining destination addresses is specific to each discovery service and must be implemented accordingly.

## Actual Behavior / Motivation for New Feature
The polling of discovery services at long intervals is motivated by performance problems. Obtaining the list of services for each request can have a negative impact on gateway performance. 

Polling is already implemented for Consul, but also for Kubernetes. Unfortunately, the two providers are implemented in different ways. 

So the aim here is to propose a generic implementation of polling so that it can be offered for any type of discovery service (eg. Eureka).

## Specifications

  - Version: latest, 19.x & .NET 7

### PR DESCRIPTION
**Pull request by ggnaegi**
## Closes #1708 
- #1708 

Providers included: Consul, Eureka, etc?...

## Proposed Changes
- Introduce `PollingServicesManager<T, TU>` for generic cluster management
- Introduce `ServicePollingHandler<T>`  for generic destinations management and polling
- Use the standardized classes in `PollConsul`, `PollKube`
- Introduce `PollEureka`

### CODE REVIEW

**Comment by ggnaegi** [comment]
@raman-m This is the PR we talked about, including a generic polling manager.

**Comment by raman-m** [comment]
Thanks for the PR! 👍 

You have to update your feature branch from **develop** one! ... because of this commit e5f31ef030a4004579da8c54d663721ffb58fa22 after merging #1711 
And, unfortunately you have to resolve merge conflicts! 😢 

Please be very accurate in such kind of PRs with aggressive refactoring! Watch for interconnections, double check facts, and of course care about all tests.
I will return to your PR back after current release these days...
Thanks you!
Having a good start of the week!... 🍂 (autumn mood)

**Comment by ggnaegi** [comment]
> Thanks for the PR! 👍
> 
> You have to update your feature branch from **develop** one! ... because of this commit [e5f31ef](https://github.com/ThreeMammals/Ocelot/commit/e5f31ef030a4004579da8c54d663721ffb58fa22) after merging #1711 And, unfortunately you have to resolve merge conflicts! 😢

@raman-m merge is done, but I will review the code once or twice and let you know.

**Comment by raman-m** [comment]
Don't you like your idea described in #1708 ?

**Comment by ggnaegi** [comment]
@raman-m Well, I don't like bashing, it's not my way of looking at things. I was happy to help, but that's all.

**Comment by ggnaegi** [comment]
@raman-m a new provider project is needed for ServiceFabric... Can I create a new project in the solution?

**Comment by ggnaegi** [comment]
@raman-m could you reassign me please?

**Comment by raman-m** [comment]
>@ggnaegi commented [on Oct 15](#issuecomment-1763472645)

You're [assigned](#event-10666132975)! 😉

**Comment by raman-m** [comment]
Rebasing feature branch is required!

**Comment by raman-m** [comment]
Wow! I remember this PR... 😄 
It is not planned for any milestones..
What is the approximate readiness now?

**Comment by ggnaegi** [comment]
> Wow! I remember this PR... 😄 It is not planned for any milestones.. What is the approximate readiness now?

Still a bit of work, but we could foresee it for the december release.

**Comment by raman-m** [comment]
@ggnaegi Multiple conflicts! Please resolve them!

>Still a bit of work, but we could foresee it for the december release.

Well... Dec'23 release is closed. Do you want to include it to Jan'24 release on Feb 23 or leave it in Annual'23 one?
Will 1 week be sufficient to finish the PR?

**Comment by ggnaegi** [comment]
@raman-m this should be part of Annual release, first address the consul long polling issue.

**Comment by raman-m** [comment]
@ggnaegi 
I can't have a quick resolving of all these merge conflicts. I don't know the logic, there are a lot of conflicts.
So, **I can't rebase the branch onto target!**

### Could you resolve merge conflicts please?

Don't forget to make backup copied branch or copy whole solution to a separate folder.

**Comment by ggnaegi** [comment]
> @ggnaegi 
> I can't have a quick resolving of all these merge conflicts. I don't know the logic, there are a lot of conflicts.
> So, **I can't rebase the branch onto target!**
> 
> ### Could you resolve merge conflicts please?
> 
> Don't forget to make backup copied branch or copy whole solution to a separate folder.

@raman-m I think I will need to rewrite it since I'm preparing a PR with the long polling for consul...

**Comment by raman-m** [comment]
So, is this PR dependent on a PR which will be created soon? Why keep this open? Mark draft?

Do you need to re-write this PR keeping it open, or will you close this PR and open new one after dependency removed?

**Comment by ggnaegi** [comment]
> So, is this PR dependent on a PR which will be created soon? Why keep this open? Mark draft?
> 
> Do you need to re-write this PR keeping it open, or will you close this PR and open new one after dependency removed?

I think I will close this PR, open a new one with the long polling for the consul provider... And later reopen a PR with a generalized mechanism. Keep it as a draft for now.

**Pull request closed without merging**
