### PR TITLE
Fix Formatting and Misspellings on Error Codes Doc

### PR DESCRIPTION
**Pull request by btull89**
# Fixes

## Proposed Changes

  - Fix markdown formatting preventing list from being rendered
  - Fix miscellaneous misspellings.

### CODE REVIEW

**Review by EngRajabi — APPROVED** [review]
ok

**Review by raman-m — APPROVED** [review]

**Comment by raman-m** [comment]
@btull89
Hi Brandon!
Thanks for your interest in Ocelot gateway!

I've made some improvements (see my commits) and approved the PR finally.

**Comment by raman-m** [comment]
Duplicate of #1678

**Comment by btull89** [comment]
> @btull89 Hi Brandon! Thanks for your interest in Ocelot gateway!
> 
> I've made some improvements (see my commits) and approved the PR finally.

Sounds good. Thank you

**Comment by raman-m** [comment]
Duplicate of https://github.com/ThreeMammals/Ocelot/pull/1678

**Pull request closed without merging**
