### PR TITLE
adding read the docs yaml config file

### PR DESCRIPTION
**Pull request by ggnaegi**
Fixes / New Feature #1731

## Proposed Changes
  - add .readthedocs.yaml file to the root folder.
https://blog.readthedocs.com/migrate-configuration-v2/

I just tried myself
https://ocelot-test.readthedocs.io/en/latest/features/authentication.html

@raman-m it seems too easy, no?

### CODE REVIEW

**Comment by raman-m** [comment]
Wow! Thank you for caring about our project during your weekend!

I've planned to work on docs recovery after the release, but as usual I had no time for that. It seems you beat me.

### Question
What branch you've created the feature branch from?
In my opinion it should be hotfix.
So, we have to use current release branch `release/20.0` or `main` one. But release branch is better choice.

**Comment by ggnaegi** [comment]
> Wow! Thank you for caring about our project during your weekend!
> 
> I've planned to work on docs recovery after the release, but as usual I had no time for that. It seems you beat me.
> 
> ### Question
> What branch you've created the feature branch from? In my opinion it should be hotfix. So, we have to use current release branch `release/20.0` or `main` one. But release branch is better choice.

@raman-m I have used the develop branch. I can delete the current PR an create a new one based on branch release/20.0

**Comment by raman-m** [comment]
Yes, please close! We can't wait till the next major release of features in develop.
So, it will be a hotfix for the **20.0** release.

**Create feature branch from `release/20.0` one please!**

**Comment by ggnaegi** [comment]
@raman-m as discussed, closing the PR

**Pull request closed without merging**
