### PR TITLE
Fixed logger message typos in the OutputCacheMiddleware class

### PR DESCRIPTION
**Pull request by thiagoloureiro**
## Proposed Changes

Fixed typos in the log when caching:
- [fixed typo in log](https://github.com/ThreeMammals/Ocelot/pull/1315/commits/e74a568a21f8c3e7125ec04e2b7f07faf94992a3)
- [Fix typos and improve logger messages for OutputCacheMiddleware](https://github.com/ThreeMammals/Ocelot/pull/1315/commits/c7c11c935c4400e97e8fc5e1dc22f605bf954d7b)

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
@TomPallister  this is a simple one, can you approve pls?

**Comment by raman-m** [comment]
@thiagoloureiro 
Hi Thiago!

I've made some improvements in this PR and committed them.
The PR has been approved by me!

I see that there is no activity from your side for more than one year.
And your [last commits](../commits?author=thiagoloureiro) in **develop** branch were merged in 2019...
Do you have an intention to be the member of Ocelot team further?

**Comment by raman-m** [comment]
@TomPallister  Could you review and merge the PR please? 
I am still not able to merge PRs...

**Comment by thiagoloureiro** [comment]
> @thiagoloureiro 
> 
> Hi Thiago!
> 
> 
> 
> I've made some improvements in this PR and committed them.
> 
> The PR has been approved by me!
> 
> 
> 
> I see that there is no activity from your side for more than one year.
> 
> And your [last commits](../commits?author=thiagoloureiro) in **develop** branch were merged in 2019...
> 
> Do you have an intention to be the member of Ocelot team further?
> 
> 

Why those questions? We all have full time jobs and we contribute when we can. I don't get your comments asking if I still want to be part of it..

**Pull request merged**
