### PR TITLE
Upgrade to net7

### PR DESCRIPTION
**Pull request by RaynaldM**
- Upgrade to .net 7.0 most of projects in solution
- Update of many packages (but not all: some are not compatible and/or require adaptations)
- Partial reformatting and partial code cleaning
- Slight modernization of the code (but much remains to be done)

### CODE REVIEW

**Comment by TomPallister** [comment]
Thanks for submitting this! A massive PR!!! If anyone is watching this PR please comment with any feedback. I will try and review and merge it within the next week.

**Comment by raman-m** [comment]
@RaynaldM You forgot to link your issue #1640 in Development section (right side).
I would love to review the PR if you add me to Reviewers please.

**Comment by RaynaldM** [comment]
> @RaynaldM You forgot to link your issue #1640 in Development section (right side). I would love to review the PR if you add me to Reviewers please.

I don't know why, but I cannot modify my issue

**Comment by raman-m** [comment]
For a some reason Tom did not assign me this PR.

@RaynaldM Are you able to assign me this PR (add to Reviewers)? You're the author, so, I believe you should be able to make me as reviewer.
Otherwise, you need to add me as collaborator to your forked repo [RaynaldM/Ocelot: .NET core API Gateway](/RaynaldM/Ocelot) via repo Settings -> Access -> Collaborators page.
The problem is that a reviewer should have Write access for a PR to review it and finally having reviewing result as green checkmark. Only green checkmarks allow to merge PR.
More about PR permissions here:  [About pull request reviews - GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).
Read the Tips plz!

**Comment by TomPallister** [comment]
I had to add you to the team! I'm just trying to get the build working with dotnet 7

**Comment by raman-m** [comment]
Hi @TomPallister ! Thanks for adding to the team! 😍 
Hope we will make Ocelot better. 😄 
Just having a nice weekend spending!

**Comment by raman-m** [comment]
@TomPallister  While you are fighting with builds (CI-CD, Circle CI ?)... Here is the first review result regarding tests.
I've done some comparison of solutions stability from both branches. After running all tests in Test Explorer:

PR1645-Ocelot-tests-net6-net7-comparison
Left side, source branch solution ([RaynaldM:upgrade-to-net7](https://github.com/RaynaldM/Ocelot/tree/upgrade-to-net7))
Right side, target branch solution ([ThreeMammals:develop](https://github.com/ThreeMammals/Ocelot))
It seems everything is fine, I have ran multiple times. So, the behavior is pretty stable in both solutions. Nothing got worse, possibly, from the point of view of building pipeline.
But the number of tests has been decreased: 813 down to 808. +1 skipped test. So, total 5 tests were removed.
I have no list of removed tests. Should we make the list and review them, and why were they removed?
I guess that some tests are failing after the upgrading. That's why Raynald had removed them from test projects. 

@RaynaldM Could you help us the extract the list of removed tests please? Did they turn red?

**Comment by TomPallister** [comment]
I went through all the files and fixed the build...it probably wont work but I will mess around until it does then release a new package from main branch!

**Comment by raman-m** [comment]
@TomPallister What about tests?
Too late! You did it! 😄 PR has been merged.

**Comment by TomPallister** [comment]
the skipped test was a theory so I think thats why 5 were missing

**Comment by TomPallister** [comment]
I didnt see any tests that had been deleted

**Review by raman-m — COMMENTED** [review]
@TomPallister Just a post-review after your merging.
As Raynald has already mentioned I saw these major changes
- Targeting framework from **net6** to **net7**
- Increasing the versions of NuGet packages including the support of **net7**
- A lot of styling and formatting changes, and fixing of StyleCop analyzer's issues

So, the code looks more modern now, having latest C# versions sentences.
After fixing of StyleCop warnings and errors, I would say that the source code has much better readability.

Finally, it seems there is no breaking changes in the code. There are code improvements in similar to Microsoft coding conventions. I guess StyleCop of the **1.2.0-beta.435** version did the job! 😁 
Congrats on final merging the PR! ✌️ 

@RaynaldM  Good job! 👑

**Pull request merged**
