### PR TITLE
#749 Bad error handling for `IOException` while reading incoming request body

### LINKED ISSUE #749: Bad error handling for IOException while reading incoming request body
## Expected Behavior

If an `IOException` happens while reading the incoming request body (in `RequestMapper.MapContent` [here](https://github.com/ThreeMammals/Ocelot/blob/02e5cea7b1bdd3d78cfe1a5bb688383f54a809fc/src/Ocelot/Request/Mapper/RequestMapper.cs#L24)), Ocelot fails the request with an `UnmappableRequestError` and status code 404.

404 is not appropriate, and the error logged by ocelot should be more specific than `UnmappableRequestError`. It just so happens that the exception happens while doing request mapping, but it's really an IO problem while reading the incoming request stream. Response status shouldn't be 404. In the case of too large request, 400 might be appropriate. In other cases, something in the 5xx range.

## Steps to Reproduce the Problem

This happens consistently, for example, for requests that are too large for the server (`HttpSys` throws an IOException if the Content-Length of the incoming request is larger than 30MB by default -- see: [AspNetCore source](https://github.com/aspnet/AspNetCore/blob/cd0eab88eaa230fa276c27ab5dc71ea267efe14f/src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs#L435-L436)).

  1. Send a request to Ocelot, hosted on HttpSys, with Content-Length larger than 30,000,000.
  1. Boom!

Ocelot returns 404, and logs `UnmappableRequestError`.

## Specifications

  - Version: 12.0.1 (should also apply to 13.0.0 by code inspection)
  - Platform: Windows Server 2016 / .NET Framework 4.6.2

### PR DESCRIPTION
**Pull request by ggnaegi**
## Fixes #749 
- #749 

The error handling in ocelot is hiding the 413 payload too large exception. As @raman-m pointed out, a deeper error handling review is needed. Here, I have implemented a quick fix to this issue and I would recommend opening a new issue for the error handling review. 

## Proposed Changes
  - Handling `BadHttpRequestException` and if status code == 413, then returning a `PayloadTooLargeError`
  - Adding two acceptance tests for kestrel and **HttpSys** instances

### CODE REVIEW

**Comment by raman-m** [comment]
Please, resolve conflicts!

**Comment by ggnaegi** [comment]
@raman-m you can review it

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
@ggnaegi commented [on Dec 14](https://github.com/ThreeMammals/Ocelot/pull/1769#issuecomment-1854929755)

Thanks for update!
Not urgent. Not planned.
I'll review after the current [Nov'23](https://github.com/ThreeMammals/Ocelot/milestone/2) release... You know we're focusing on it now...

**Comment by ggnaegi** [comment]
> @ggnaegi commented [on Dec 14](https://github.com/ThreeMammals/Ocelot/pull/1769#issuecomment-1854929755)
> 
> Thanks for update! Not urgent. Not planned. I'll review after the current [Nov'23](https://github.com/ThreeMammals/Ocelot/milestone/2) release... You know we're focusing on it now..

@raman-m but we discussed this... remember

**Comment by raman-m** [comment]
@ggnaegi  Please resolve conflicts and rebase onto develop!
I need to decide on release version to include it into. What's readiness of the PR? Will you develop more?
If it is highly ready then we can add the PR to Jan'24 release.

**Comment by ggnaegi** [comment]
@raman-m Yes, it can be part of Jan 24 Release

**Comment by raman-m** [comment]
@ggnaegi  Please resolve conflicts!

**Review by raman-m — APPROVED** [review]
Ready for delivery! ✅ 
- Code review ✔️ 
- Team approvals ✔️ 
- Unit testing ✔️ 
- Acceptance tests ✔️✔️

**Pull request merged**
