### PR TITLE
fix: minor grammar fix in default rate limit response message

### PR DESCRIPTION
**Pull request by eddex**
Continue with upper-case letter after exclamation mark in default rate limit response message.

### CODE REVIEW

**Review by MehdiSadeghi1996 — APPROVED** [review]

**Review by raman-m — APPROVED** [review]
Yet another micro PR is approved! 😄

**Comment by raman-m** [comment]
@TomPallister  Hi Tom!
Merging is blocked! Even for such kind of tiny PRs. So, I have no right to merge being a member of Ocelot org. :(
Could you auto-approve please? Builds are green.

**Comment by eddex** [comment]
Thanks for the review. Glad to see that there is still work being done on Ocelot! I was already a bit worried that the project might have been abandoned 😅

**Comment by raman-m** [comment]
Duplicate of #1678 

@eddex  Thank, you, Marco!

**Comment by raman-m** [comment]
[eddex](https://github.com/eddex) commented [on Jul 11, 2023, 7:30 AM](1678#issuecomment-1630223167)
> With PR #1678 , all original commit authors were removed from the commits. **This is very disrespectful to say the least..**

[eddex](https://github.com/eddex) commented [on Jul 11, 2023, 7:25 AM](#issuecomment-1630218061)
> You copy my changes to your own (newly created) PR and close my PR as duplicate, taking full ownership of the changes I (and many other people) made for yourself. **That's just rude.**

---
So sad to see such emotional reaction from you!

**Comment by raman-m** [comment]
Dear Marco,

Sorry for closing your PR! 
I am not going to explain you the reasons of creation of PR #1678: everything is explained/described in linked issue.
I've decided to reopen this PR for your own management.
If your current PR will be merged first I will remove the changes from my one. Deal?

You may ask Tom personally to merge this PR.
Good luck!

**Review by raman-m — APPROVED** [review]

**Review by raman-m — APPROVED** [review]

**Pull request merged**
