### PR TITLE
Fix empty the '_services' list during first access using PollConsul

### PR DESCRIPTION
**Pull request by 0xblack**
Solves the bug where the first access _services empty when using PollConsul

### CODE REVIEW

**Comment by raman-m** [comment]
@0xblack Hi **wuhuajun**!
After merging latest top commits from **base:develop** and after running of CI pipeline,
we have one failed unit test:
```
Failed Ocelot.UnitTests.Consul.ProviderFactoryTests.should_return_PollingConsulServiceDiscoveryProvider
```
Could you fix this unit test please?
And, it makes sense to cover this case by adding new unit test(s) too.

I will start review as soon as you've fixed current unit tests.

**Review by raman-m — APPROVED** [review]

**Comment by raman-m** [comment]
@0xblack Hi Wuhuajun!
Thanks for the fix!

@TomPallister 
Please, review and merge the PR!
Pay attention, this bug was mentioned in #1634 .

**Comment by raman-m** [comment]
@0xblack  Well...
Did you fix your own user case, or is the PR related to some open issue?

Also, I have intentional feeling your PR can be a duplicate... We have a number of PRs which address this `PollConsul` problem.
Let's see!
I'm going to rebase feature branch for more accurate code review...

**Comment by raman-m** [comment]
@ggnaegi 
This PR has one line change with extra synchronous call of provider ignoring asynchronous `Poll` method at all.
I have no idea, it seems calling async operations inside of constructor is not good.

What will we do with this PR, on your opinion? 😃

**Comment by ggnaegi** [comment]
@raman-m this PR should be addressed now, no?

**Comment by raman-m** [comment]
>@ggnaegi commented [on Sep 29](#issuecomment-1741329558)

Don't address at all! 😸 
I've decided to close this PR because it is useless now, after your contribution to latest release.

**Comment by raman-m** [comment]
Duplicate of #1670

**Comment by raman-m** [comment]
@0xblack
Sorry, your PR is not developed well for accepting. And this problem was addressed and bugs were fixed in #1670 
Going to close...

---
I hope you will return to us back with many interesting PRs to close items in [backlog](../issues). 😉

**Pull request closed without merging**
