### PR TITLE
Feature/603 bad gateway

### PR DESCRIPTION
**Pull request by jlukawska**
Fixes / New Feature #603 Respond with an error on no connection to downstream service

## Proposed Changes

  - return 502 Bad Gateway status code when request can not be completed
  -
  -

### CODE REVIEW

**Comment by TomPallister** [comment]
@jlukawska thanks for the PR, I'm not sure this is the correct behaviour because the error will be raised after making a http request and getting any exception from HttpClient.SendAsync which might not be caused by the service being called! What do you think?

**Comment by jlukawska** [comment]
Yes, you're right. So I've changed this to look for HttpRequestException only.

**Comment by TomPallister** [comment]
@jlukawska should Ocelot just not return the error from the service? Given that Ocelot is just a proxy? I'm really not sure :(

**Comment by jlukawska** [comment]
This post: https://github.com/ThreeMammals/Ocelot/issues/603#issuecomment-441811416 and my little research convinced me that it makes sense, but the decision is yours of course.

**Comment by TomPallister** [comment]
please open PR again against master branch

**Pull request closed without merging**
