### PR TITLE
Feat/remove ocelot middleware

### PR DESCRIPTION
**Pull request by TomPallister**
Fixes / New Feature #

In order to take advantage of Microsoft's [ YARP](https://github.com/microsoft/reverse-proxy) project. We need to remove the Ocelot specific middleware. This was used to enable request aggregation and make data available in the pipeline that isn't on HttpContext.

## Proposed Changes

  - Huge refactor that remove the Ocelot specific Middleware
  - Replaces it by accessing data from HttpContext
  - Request aggregation now works by making a copy of the HttpContext and passing this into the next middleware chain. 
  - Updated docs to reflect changes to IDefinedAggregator

### CODE REVIEW

**Comment by jmezach** [comment]
This looks interesting @TomPallister. Could you perhaps elaborate a little bit about how you see Ocelot and YARP going forward?

**Comment by TomPallister** [comment]
@jmezach I will start to to use YARP inside Ocelot....I have a lot of refactoring to make this work, over time I expect to deprecate Ocelot in favor of YARP but some of the Ocelot middleware might complement YARP.

**Comment by samsp-msft** [comment]
@TomPallister We'd be honored if you incorporated YARP into Ocelot.

While there is some overlap between YARP and Ocelot - AFAIK the goals are a bit different. In YARP we are essentially a request router, and are prioritizing performance. YARP operates on the headers of the request - the bodies are streamed and not "processed". As a API gateway, Ocelot is processing the bodies and therefore offers a richer set of functionality that we don't intend to *build in* to YARP.

One of the goals for YARP is to be extensible, and enable custom middleware to be slotted into the pipeline. The concept of adding Ocelot middleware to YARP or building Ocelot on top of YARP components is something we'd love to see as it provides a set of functionality that we are not planning to deliver and Ocelot already has a lot of happy customers.

YARP is young, and we are only just starting to define how middleware can be slotted in. If there are changes we can make to ease the slotting in of Ocelot middleware, then don't hesitate to file issues or PRs.

The secondary goal of YARP beyond providing a reverse proxy is to act as a forcing function to ensure that the underlying infrastructure and APIs in ASP.NET and networking are as performant as possible and facilitate building a high scale edge service. These changes in .NET 5(+) will probably have benefits for Ocelot or other services. For example:

* We are working on an Async callback to intercept connections as part of the TLS handshake
* Improving the performance of header processing in HttpClient
* Looking at connection management in HttpClient
* Logging improvements in ASP.NET and HttpClient

These should benefit Ocelot regardless of whether you utilize YARP infrastructure.

Please reach out if we can help in any way.

**Comment by TomPallister** [comment]
@samsp-msft Hi Sam, I'm sorry I missed this someone messaged me on LinkedIn to show it to me recently. I would be happy for someone to merge YARP into Ocelot. If you want write permission to the project let me know!

**Comment by raman-m** [comment]
@TomPallister  Hi Tom!
I am so sad that you try to kill/delegate your project to Microsoft!
Do you understand that after delegating the owner right to engineers/managers from Microsoft your project will be dead (deleted), archived or just frozen? The most optimistic scenario is just having a few updates from community being managed by Microsoft team member(s). Nothing more!
Let's wait a Sam's feedback on your request.

Another side of this Ocelot/YARP dangerous pairing is that most of members of YARP team members are Microsoft engineers.
Look at this YARP [Contributors](https://github.com/microsoft/reverse-proxy/graphs/contributors) graphs which show that the most active members of YARP are Chris and Miha. Warning! They are both true employees of Microsoft!
Of course, they can collaborate on any open-source projects on GitHub including YARP, this is their right, but it is strange the Ocelot people consider them being active collaborators of Ocelot in the future, who really cares about Ocelot Gateway destiny.
Do you expect that YARP members will contribute to Ocelot repository? Really? A couple of Microsoft employees will contribute to non-Microsoft initiative, really?

Tom, you should understand that YARP is a "competitor" of Ocelot, because there are no much .NET gateway solutions on the market that are changing the API gateway industry. I cannot predict the future of Ocelot after your delegation to Microsoft, but as a realist I expect some bad things will happen.

Why are you having an intention to delegate management of Ocelot repo? To Microsoft? Are you impressed by key benefits of YARP? Why not to take Ocelot to the next level? Constant enhancements, constant moving forward...
Are you tired with the project in 2020? Don't you have much time to manage the repo and move the project forward? I see 2-3 releases only with .NET version upgrade last 3 years.

Ok, I will watch this thread during this summer. But I don't expect extra super- productive offers for you from Microsoft.
On my opinion it is impossible to "merge" YARP to Ocelot, because there are no resources, no time, etc. And what's the final goal of such merging? In theory it is possible to merge, but it will be nightmare. Introduce a gateway inside of another one? It is strange approach. But we can discuss that.
And, I am pretty on 100% sure that Ocelot will never be merged to YARP. Just never!

Let's save the Ocelot project! Do not delegate owner right to this corporation please! To someone else, but **not to Microsoft**!
Hope you understand!
And sorry, I had to express myself directly.

**Comment by TomPallister** [comment]
@raman-m I understand your point of view! I don't really see YARP as a competitor...I don't really care about competition though! If someone from MS wants to implement YARP to do the heavy lifting inside Ocelot then that surely is a good thing? I doubt they will though!

In terms of maintaining Ocelot I will always update it to the latest version of dotnet but I don't have time to look after the project more than that now. Someone would have to pay me a full time salary and no one has ever offered :) Who knows I may get back into it one day! My current job is all nodejs so that took me away from the world of dotnet :(

**Comment by raman-m** [comment]
@TomPallister 
> I doubt they will though!

I think so too! :rofl: 
Forget about Yarp! This is a good product made by Microsoft engineers. But this project has a completely different philosophy and the goal (I have some feelings but don't want to express them). So, Yarp is developing for some Microsoft needs. It is like a laboratory for networking tools. This is my opinion.
And I believe Ocelot has completely different philosophy on my opinion. Ocelot is an open-source .NET gateway for a lot of startups in the world. Isn't it wonderful?
Some people said that: _"Yarp is production ready, but Ocelot not"_. This is wrong! Sure, Yarp can be a part of production ready software even for enterprises. What's the problem when enterprises will use Ocelot?
Some people said that: _"Yarp has super performance in proxying traffic, but Ocelot has worst performance"_. OK. But having a super performance of software for enterprises, such unicorns have big DevOps and Development departments to build and link all services communication without any gateways! This is super performant to link two service endpoints directly without gateways, without Ocelot, without Yarp.
Another vision is that modern cloud service providers like Azure, Aws allow to build direct communication without any gateways.

Finally, I would say that Ocelot and Yarp cover different markets: Yarp will cover Enterprises and large business, and Ocelot can cover markets for medium, mini, micro businesses in the world, including startups.

> Someone would have to pay me a full time salary and no one has ever offered :)

But I cannot too! :smile_cat: 
Look into my LinkedIn profile: [Raman Maksimchuk | LinkedIn](https://www.linkedin.com/in/raman-m/)
My avatar has #OpenToWork badge. I have lost my full time job more that one year ago.
So, I cannot hire you to develop your project. :rofl: 
I could invest or donate some money to the development of Ocelot to support the project. But I need more rights in the project.
Tom, it is time to decide! This summer...
I will be very glad if you come back to the project in future spending most of the day, but I don't expect that. And I don't wish you to lose any full time jobs! One our member of Ocelot team said: "We all have full time jobs, why..."

Anyway,
For now it will be performant if you review current open PRs on **monthly** basis and merge those PRs which have "Accepted" label with approvals enough. Better to check **biweekly**. Checking & Merging PRs **weekly** is super cool!
Read my latest message in LinkedIn chat please. I will share my significant ideas via LinkedIn only.

Happy Friday! And, have a great summer!
Raman

**Comment by raman-m** [comment]
@TomPallister 
I hope your summer and vacation were just great! 🌞 

Congratulations with promotion to VP of Technology at [News UK](https://www.linkedin.com/company/news-uk/)! 🎉 
Now I completely understand why you are so busy. 🥇 
It seems it is time to close [ThreeMammals](/ThreeMammals) org. It is a joke! 😉

⚠️ **It is definitely right time to decide!** See [LinkedIn](https://www.linkedin.com/in/raman-m) messaging chat please. 🙏

**Pull request merged**
