### PR TITLE
#1351 #1510 New AddOcelot extensions to support custom ASP.NET MVC pipeline building via the IMvcCoreBuilder interface

### LINKED ISSUE #1351: Ocelot overides System.Text.Json parser and uses Newtonsoft
## Expected Behavior / New Feature
When try using ocelot, Newtonsoft parser is used, but i want to use System.text.json

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

### PR DESCRIPTION
**Pull request by guoyongchang**
## Closes #1351 #1510 
- #1351 
- #1510 

## Background
The default `AddOcelot` method adds `.AddNewtonsoftJson()`, which was necessary when Microsoft did not launch the `System.Text.Json` library, but now it affects normal use, so this PR is mainly to solve the problem problem.
> 默认的`AddOcelot`方法内部添加了`.AddNewtonsoftJson()`，在微软没有推出`System.Text.Json`库的时候是有必要的，但是现在反而影响了正常使用，所以本PR主要是解决该问题。

## New Feature
Added the following methods in `Ocelot.DependencyInjection.ServiceCollectionExtensions`
> 在`Ocelot.DependencyInjection.ServiceCollectionExtensions`添加了以下方法
- `AddOcelotWithCustomMvcCoreBuilder(this IServiceCollection services, Func<IMvcCoreBuilder, Assembly, IMvcCoreBuilder> customMvcCoreBuilder)`
- `AddOcelotWithCustomMvcCoreBuilder(this IServiceCollection services, IConfiguration configuration, Func<IMvcCoreBuilder, Assembly, IMvcCoreBuilder> customMvcCoreBuilder)`

## Proposed Changes
  - Support custom `MvcCoreBuilder` to adapt to more changes in the future, this change is mainly to support `System.Text.Json`
    > 支持自定义`MvcCoreBuilder`，以适应未来更多的变化，本次更改主要是为了支持`System.Text.Json`

### CODE REVIEW

**Comment by guoyongchang** [comment]
@raman-m This PR allows users to use their desired JSON library for serialization, such as System.Text.Json.

For example:

```csharp
service.AddOcelotWithCustomMvcCoreBuilder((builder,assembly)=>{
  return mvcCoreBuilder.AddApplicationPart(assembly)
    .AddControllersAsServices()
    .AddAuthorization()
    .AddJsonOptions(); // use System.Text.Json.
});
```

This is just one of the common usages, users can add more modules they need in the builder.

**Comment by raman-m** [comment]
Related to: #1515

**Review by raman-m — CHANGES_REQUESTED** [review]
Hi @guoyongchang ! I'm just curious, what's your name?
I've made some refactoring and styling issue fixes. Hope it is useful! 😸 

Could you add your user scenario from your [the comment](#issuecomment-1556176092) as acceptance test please, to make sure new Json lib is used?
You are welcome to show more techniques with MVC core builder.

Also, I am pleasantly asking you to add unit tests for new extension methods to files: [OcelotBuilderTests](../blob/develop/test/Ocelot.UnitTests/DependencyInjection/OcelotBuilderTests.cs#L39)
Or make new code files in the folder: [DependencyInjection](../tree/develop/test/Ocelot.UnitTests/DependencyInjection)

**Comment by guoyongchang** [comment]
> Hi @guoyongchang ! I'm just curious, what's your name? I've made some refactoring and styling issue fixes. Hope it is useful! 😸
> 
> Could you add your user scenario from your [the comment](#issuecomment-1556176092) as acceptance test please, to make sure new Json lib is used? You are welcome to show more techniques with MVC core builder.
> 
> Also, I am pleasantly asking you to add unit tests for new extension methods to files: [OcelotBuilderTests](../blob/develop/test/Ocelot.UnitTests/DependencyInjection/OcelotBuilderTests.cs#L39) Or make new code files in the folder: [DependencyInjection](../tree/develop/test/Ocelot.UnitTests/DependencyInjection)


@raman-m 

You can call me guo, and the name of github is my full Chinese name in pinyin. Maybe you can understand Yongchang Guo?

Nice change. I've tested it with no problems, and there will be no other confusion caused by shortened method names.

---

I think this function is usually used when integrating with existing API projects, so I put the unit test in `Ocelot.IntegrationTests`, which I think is more appropriate here.
If it is a pure gateway project, this extension method should not be used, and Newtonsoft.JSON can meet all the needs of users.

About more techniques with MVC core builder, I think that as long as a custom method is provided, all the default things can be overridden, for example, I only need to change the default Json Provider, maybe others need to add more assemblies, or change the default authentication.

---
Wrote into `Ocelot.IntegrationTests`

**Review by raman-m — APPROVED** [review]
```diff
+ Approved
```
Thanks, Guo!
Good job!

**Comment by raman-m** [comment]
@geffzhang  Could you review please?

**Review by geffzhang — DISMISSED** [review]

**Comment by TomPallister** [comment]
Thank you for the PR, please fix the merge conflicts and update the docs so people know how to use this and I'm happy to merge!

**Comment by raman-m** [comment]
@geffzhang  Geff,
Sorry for dismissing of your stale review!
Could you review and approve the PR once again please?

**Review by raman-m — DISMISSED** [review]
- Merge conflicts have been resolved after updating with new top commits from **develop** branch
- Added new [**Dependency Injection**](https://github.com/guoyongchang/Ocelot/blob/feat/supportCustomOcelotMvcBuilder/docs/features/dependencyinjection.rst) feature in documentation
- Added unit tests for the `OcelotBuilder` class to cover `AddOcelotUsingBuilder` methods

**Comment by raman-m** [comment]
@TomPallister wrote [on Jun 4, 2023](#issuecomment-1575586232)
> Thank you for the PR, please fix the merge conflicts and update the docs so people know how to use this and I'm happy to merge!

**Done!** See [the message](#pullrequestreview-1482040562) above plz!

Tom, could you review and merge it please?

**Review by raman-m — APPROVED** [review]

**Comment by raman-m** [comment]
@guoyongchang  Hey Guo!
I am really wondering, don't we have [something similar](/search?q=repo%3AThreeMammals%2FOcelot+AddOcelot&type=issues) in [backlog](../issues) to link this PR to?
We need to look at current open issues and relate some of them to this PR...

**Comment by raman-m** [comment]
The [feature branch](/guoyongchang/Ocelot/tree/feat/supportCustomOcelotMvcBuilder) has been [rebased](#event-10315980107) onto [ThreeMammals:develop](../tree/develop)!
I would like to initiate the 2<sup>nd</sup> code review. It remains accepted though.

**Comment by raman-m** [comment]
@guoyongchang 

I see that [develop](/guoyongchang/Ocelot/tree/develop) branch in [your fork](/guoyongchang/Ocelot/branches) is [old](/guoyongchang/Ocelot/compare/develop...ThreeMammals:Ocelot:develop) and it has [some diff](../compare/develop...guoyongchang:Ocelot:develop). Is this **diff** important?

Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, **develop** branch will be updated with all top commits!

Could you [add me as collaborator](/guoyongchang/Ocelot/settings/access) to your forked repo please? I will update **develop** branch and make it identical to the base branch.

**Review by RaynaldM — APPROVED** [review]

**Review by raman-m — APPROVED** [review]
@guoyongchang Congrats! 🎉 
This feature will be released soon, on October 1.

**Pull request merged**
