### PR TITLE
#1093 Add Retry mechanism based on Polly

### LINKED ISSUE #1093: Retry calls to downstream
Hi! 

Like Ocelot is already using Polly. Is there a way to retry X times the calls to downstream to prevent occasionally fails?

### PR DESCRIPTION
**Pull request by ks1990cn**
## Closes #1093 
- #1093 

This is proposed solution to add WaitAndRetry mechanism of Polly, which is currently not part of Polly (QoS). 

This is not proper solution, this just I am trying to understand high level changes we need to add WaitAndRetry. I have not done any refactoring.

## Proposed Changes

  - Here we are facing everytime we create request, it creates new policy everytime which causes failure of WaitAndRetry mechanism. Also acknowledged by @ggnaegi in case of circuitbreaker. We need to fix it.
  - We can see only circuitbreaker is implemented, we need to create one abstraction and delegatehandling so we can add multiple policies. 
  - Test cases and need to clean this code.
  
  @ggnaegi @raman-m Can we discuss on https://github.com/ThreeMammals/Ocelot/issues/1093 with this proposed solution? I am unable to dedicate much time on learning Ocelot. But I think we have to think on above points.

### CODE REVIEW

**Comment by raman-m** [comment]
@ks1990cn 
> Can we discuss on https://github.com/ThreeMammals/Ocelot/issues/1093 with this proposed solution?

Sure! I propose to remove Polly from Ocelot at all!... Because Polly is a constant source of issue/bugs being reported in our [backlog](../issues).

**Comment by raman-m** [comment]
Dear Tanmay,
Could you resolve all merge conflicts please?

**Comment by ks1990cn** [comment]
> Dear Tanmay, Make it ready for review! Could you resolve all merge conflicts please?

But I thought you guys are going to remove Polly. do I still need to resolve, cause its incomplete PR just had suggestion on it.

**Comment by raman-m** [comment]
> But I thought you guys are going to remove Polly.

Not now. It was a joke! 🤣 
Polly removal is not discussed at the moment. It is just my idea to have less dev pain in the neck...
At least next 2 major Ocelot releases will have Polly lib being referenced definitely...

**Pull request closed without merging**
