### PR TITLE
Applied the newer code analysis rules.

### PR DESCRIPTION
**Pull request by EngRajabi**
add .net code analyzer and improve code. 
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#code-analysis-properties
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-7

### CODE REVIEW

**Comment by raman-m** [comment]
Mohsen, 
Thanks for submitted PR!
But...
- I assigned low priority for such kind of styling improvements
- Next time a PR without attached issue or linked discussion will be closed automatically without an explanation, for now I will keep it open but with low priority
- You've expressed your personal vision of stylings & conventions, so I would say it must be discussed first
- You have to focus on [current open PRs](../pulls/EngRajabi) by you!!!
- If the author has 1-2 open PRs the next PRs will be closed automatically because in my opinion contributor cannot keep another PRs opened ignoring actual work on them

P.S. Focus on [current open PRs](../pulls/EngRajabi) please!

**Comment by raman-m** [comment]
Another problem:
### There is no build at all!
You're requesting merge from a feature branch which was created from a branch which has commits which don't belong to target branch! That's why GitHub cannot decide which workflow should be run for the current feature branch to trigger building pipeline.

By other words, you have [develop branch](/EngRajabi/Ocelot/tree/develop) in your forked repo which is not identical as [ThreeMammals:develop](../tree/develop)! The [comparison diff](../compare/develop...EngRajabi:Ocelot:develop) of both branches must be zero!
You did the mistake while merging [PR 9](/EngRajabi/Ocelot/pull/9) in your repo. You pressed `Merge pull request` button instead of `Rebase and merge` one. As I pointed your attention in [this comment](/EngRajabi/Ocelot/pull/9#issuecomment-1741836746), the best approach is just watching the changes in head repo and press `Sync fork` button which will perfectly synchronize your **develop** branch to head repo one! So, both **develop** branches will be identical always if you use `Sync fork` button!
Is it too difficult to understand?
I create PRs for you to sync develop just to pint your attention that your develop branch is outdated.

----
### How to recover from blocked state
1. Run this script to recover your develop branch:
```shell
git switch develop
git reset --hard HEAD~1
```
2. After that press **Sync fork** for develop branch. The [comparison diff](../compare/develop...EngRajabi:Ocelot:develop) must be zero after the sync. If Yes, both branches are identical.

3. After that rebase your feature branch onto develop branch (better in Visual Studio) and make force push to origin:
```shell
git checkout feat_addanalyzor # it must be checked out during rebasing in Visual Studio
git push --force
```

**Comment by raman-m** [comment]
Dear Mohsen,
Don't do such mistakes next time plz!
I'm a little tired of your mistakes in all your PRs. It is pretty clear thing to try to follow development process.

**Comment by raman-m** [comment]
### You must create an issue first, or open discission thread in [Discussions](../discussions) space!
So, this PR is marked as draft.

**Comment by EngRajabi** [comment]
> Mohsen, Thanks for submitted PR! But...
> 
> * I assigned low priority for such kind of styling improvements
> * Next time a PR without attached issue or linked discussion will be closed automatically without an explanation, for now I will keep it open but with low priority
> * You've expressed your personal vision of stylings & conventions, so I would say it must be discussed first
> * You have to focus on [current open PRs](../pulls/EngRajabi) by you!!! Why do you create the next one?
> * If the author has 1-2 open PRs the next PRs will be closed automatically because in my opinion contributor cannot keep another PRs opened ignoring actual work on them
> 
> **P.S. ⚠️ Focus on [current open PRs](../pulls/EngRajabi) please!**

These changes include the following improvements that affect performance، Security improvements, productivity and...

**Comment by EngRajabi** [comment]
> Another problem:
> 
> ### There is no build at all!
> You're requesting merge from a feature branch which was created from a branch which has commits which don't belong to target branch! That's why GitHub cannot decide which workflow should be run for the current feature branch to trigger building pipeline.
> 
> By other words, you have [develop branch](/EngRajabi/Ocelot/tree/develop) in your forked repo which is not identical as [ThreeMammals:develop](../tree/develop)! The [comparison diff](../compare/develop...EngRajabi:Ocelot:develop) of both branches must be zero! You did the mistake while merging [PR 9](/EngRajabi/Ocelot/pull/9) in your repo. You pressed `Merge pull request` button instead of `Rebase and merge` one. As I pointed your attention in [this comment](/EngRajabi/Ocelot/pull/9#issuecomment-1741836746), the best approach is just watching the changes in head repo and press `Sync fork` button which will perfectly synchronize your **develop** branch to head repo one! So, both **develop** branches will be identical always if you use `Sync fork` button! Is it too difficult to understand? I create PRs for you to sync develop just to pint your attention that your develop branch is outdated.
> 
> ### How to recover from blocked state
> 1. Run this script to recover your develop branch:
> 
> ```shell
> git switch develop
> git reset --hard HEAD~1
> ```
> 
> 2. After that press **Sync fork** for develop branch. The [comparison diff](../compare/develop...EngRajabi:Ocelot:develop) must be zero after the sync. If Yes, both branches are identical.
> 3. After that rebase your feature branch onto develop branch (better in Visual Studio) and make force push to origin:
> 
> ```shell
> git checkout feat_addanalyzor # it must be checked out during rebasing in Visual Studio
> git rebase --onto develop feat_addanalyzor # but it is better to do rebasing in Visual Studio
> git push --force
> ```

I merged your Develop branch on my Develop branch.

**Comment by raman-m** [comment]
>@EngRajabi commented [on Oct 13](#issuecomment-1761629790)
> I merged your Develop branch on my Develop branch.

OK, you've merged.
But did you follow the instructions?
Did you resolve the problem of feature branch building?
Did you understand the problem?

**Comment by raman-m** [comment]
Look at [Files changed](1729/files), and it has nothing:
### These merge commits were added into this branch cleanly.
Your feature branch is invalid, it's broken now!
This PR will be closed because of **zero changes**.

**Comment by raman-m** [comment]
> @EngRajabi commented [on Oct 13](#issuecomment-1761626399)
These changes include the following improvements that affect performance، Security improvements, productivity and...

I am tired! Sorry! And I don't care about your requests...

**Comment by raman-m** [comment]
> [EngRajabi](https://github.com/EngRajabi) commented [on Oct 12](#issue-1940020139)

- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#code-analysis-properties
- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-7

Hi @ggnaegi !
I know you love code quality tools, static analyzers and code scanners...
How useful are these links to read and understand a benefit for our project?

I use Visual Studio of latest version, and IDE just has built-in static analyzers like CA* and IDE* messages during local builds. I try to fix all reported issues.
Also, we have enabled StyleCop analyzer with predefined rules, which is pretty useful. So, trying to fix all reported errors & warnings & messages makes the code much better.
I am just cannot get, what benefits will we earn if we review the project by approaches written in the docs of these links?
What is the benefit?

**Pull request closed without merging**
