### PR TITLE
AddOcelot support custom MvcCoreBuilder / AddOcelot支持自定义MvcCoreBuilder

### PR DESCRIPTION
**Pull request by guoyongchang**
## Background

The default `AddOcelot` method adds `.AddNewtonsoftJson()`, which was necessary when Microsoft did not launch the `System.Text.Json` library, but now it affects normal use, so this PR is mainly to solve the problem problem.
> 默认的`AddOcelot`方法内部添加了`.AddNewtonsoftJson()`，在微软没有推出`System.Text.Json`库的时候是有必要的，但是现在反而影响了正常使用，所以本PR主要是解决该问题。

## Fixes / New Feature #
Added the following methods in `Ocelot.DependencyInjection.ServiceCollectionExtensions`
> 在`Ocelot.DependencyInjection.ServiceCollectionExtensions`添加了以下方法
- AddOcelotWithCustomMvcCoreBuilder(this IServiceCollection services, Func<IMvcCoreBuilder, Assembly, IMvcCoreBuilder> customMvcCoreBuilder)
- AddOcelotWithCustomMvcCoreBuilder(this IServiceCollection services, IConfiguration configuration, Func<IMvcCoreBuilder, Assembly, IMvcCoreBuilder> customMvcCoreBuilder)

## Proposed Changes

  - Support custom `MvcCoreBuilder` to adapt to more changes in the future, this change is mainly to support `System.Text.Json`
    > 支持自定义`MvcCoreBuilder`，以适应未来更多的变化，本次更改主要是为了支持`System.Text.Json`

### CODE REVIEW

**Comment by raman-m** [comment]
Hi @guoyongchang !

Could you resolve merge conflicts please?
After that CI-CD pipelines will be triggered.

**Comment by guoyongchang** [comment]
> Hi @guoyongchang !
> 
> Could you resolve merge conflicts please? After that CI-CD pipelines will be triggered.

Conflict resolved.

**Comment by raman-m** [comment]
Now I see that at least your changes don't break current features.
But we have 2 parents in commit [Merge branch 'develop' into develop](https://github.com/guoyongchang/Ocelot/commit/b64b6b5d72afb4f01cdb6a379cb95bd678929249).
I'm not a fan of merge commits with two parents after conflicts resolution, because they make non-linear history in base branch.
You need to put your commits on the top commit in **base:develop**!

Could I ask you to re-create PR please? Unfortunately your develop is broken. Your forked develop branch must be the same as develop branch in source repo!

- Just backup these 2 files please with new changes.
- Remove current fork, and make new fork to be sure you have the same history as in source repo having all commits up to date
- Don't apply changes in develop, just keep it updated via pull operation always, just for future usage
- Create new feature branch from **develop** one, for example, feat/XXX
- Apply new changes from files backup.
- Create new PR
- Do not forget to link both PRs (old and new ones) for tracking purposes

As soon as you've created new PR, this PR will be closed as duplicate.

Finally,
Could you scan current open issues plz?
And what issue is this PR related to? Number?

**Comment by guoyongchang** [comment]
#1515

**Pull request closed without merging**
