### PR TITLE
#1811 #1804 Load balancer sample using Consul and Least Connection

### LINKED ISSUE #1811: The SSL connection could not be established - While setting up LoadBalancer using Consul and LeastConnection.
### Discussed in https://github.com/ThreeMammals/Ocelot/discussions/1804

<div type='discussions-op-text'>

<sup>Originally posted by **ks1990cn** November 24, 2023</sup>
Hi @raman-m @ggnaegi / Anyone ,

Can you please help me to resolve error mentioned in title? 
I've created 3 web api projects - 2 of them to replicate DownstreamApi Instance1 and Instance2, 1 is to replicate API Gateway.

when I try to reach downstream using upstream of API Gateway, and when it tries to find hostandport anc check for services available, it suddenly breaks stating SSL Connection could not be established.

Can you help me by cloning below code and let me know what I am missing in setup. Here is GIF of problem and code from where you can clone.

Please let me know any input required from me.

SSLissue

Code path changes I've done:
https://github.com/ks1990cn/Ocelot/tree/LoadBalancerSample</div>

### PR DESCRIPTION
**Pull request by ks1990cn**
## Closes #1811 
- #1811 

LoadBalancer Sample using Consul and Least Connection type.

I am creating this PR as a handy guide for local setup and running so any contributor can see loadbalancer in action with minimal repeated setup.

I think this can also help me / anyone as always present setup so just quickly go and make required changes to debug any requested changes / bug.

## Proposed Changes

- Under Sample folder, created LoadBalancerDemo
- This folder have 3 Services (Instance1, Instance2 - to demo 2 instances & API Gateway).
- When we hit - /hostname of API Gateway, it loadbalancer will come into picture and with least connection method it will return to which instance it is serving request.
- Ocelot.Sample.Loadbalancer.Common for setup of Consul with Instance 1 and instance 2 (Services)

### CODE REVIEW

**Comment by ks1990cn** [comment]
@ggnaegi @raman-m Please check if folder structure looks fine to you.

@ggnaegi Please help me with your last suggestion - Only one downstream API can be used to demo load balancer. In docker-compose which service instance is mentioned on first gets started based on docker image.

**Comment by raman-m** [comment]
Tanmay, I'm glad that you're so productive developer who creates 3 PRs.
Hope we will deliver this PR next year... It's a joke! In January'24 for sure. :wink: 

I will review after the Nov'23 release... sorry!

**Comment by raman-m** [comment]
No! Nov-Dec'23 release is still ongoing...
Watch for the progress in [Nov-December'23](https://github.com/ThreeMammals/Ocelot/milestone/2) milestone

**Comment by raman-m** [comment]
@ks1990cn commented [on Jan 12](https://github.com/ThreeMammals/Ocelot/pull/1860#issuecomment-1888638934):
> Are you done with Nov release?

Yes, we've released version [23.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.0.0) on Feb 13, 4 days ago.

**Comment by raman-m** [comment]
Tanmay,
What do you think is the readiness of this PR in %?
Can I review and invite other reviewers?

**Comment by ks1990cn** [comment]
Hi @raman-m ,

For this PR, @ggnaegi was suggesting that from single downstream API and using docker image for that api can demo multiple container instance and load balance it.


My previous idea was to have two downstream apis and one api for gateway to demo it. In this way I was able to demo two instances of apis.

Probably I need idea that @ggnaegi was suggesting.


Waiting to start again with you guys😬

**Comment by raman-m** [comment]
@ks1990cn commented [2 days ago](https://github.com/ThreeMammals/Ocelot/pull/1860#issuecomment-1949987337):
>For this PR, @ggnaegi was suggesting that from single downstream API and **using docker image** for that api can demo multiple container instance and load balance it.

Absolutely! Only Docker in compose configuration. Our old Samples has the same design issue, they must be refactored with Docker Compose configuration.

What was the problem just to include new Docker files? Why to close PR?
If your new PR will be on the top of [PRs list](https://github.com/ThreeMammals/Ocelot/pulls) that does not mean your new PR will be merged first. 🤣 It depends on PR readiness to deliver only.

**Comment by ks1990cn** [comment]
@raman-m I got problem with my dev branch with my fork. And I forked again. So PRs got closed due to head got deleted for them.

Problem with dev : I got 4-5 commits ahead of main branch and sync was saying I am upto date and I was not able to see your recent changes. Quite weird thing happened.

Usually, I just sync my develop & merge it to my working branch so code gets upto date!

**Comment by raman-m** [comment]
Very interesting story with fork deletion! 
Please write more fairy tales. ))

**Comment by raman-m** [comment]
Nothing mysterious! Just hash values of commits were changed after force pushing, after feature branch rebasing (on origin).
After that your local repo commits have different hash values. To fix that you had to delete and checkout the branch, nothing more!
```
git switch develop
git branch -D loadbalancer
git fetch --all
git checkout loadbalancer
```

**Pull request closed without merging**
