### PR TITLE
Manage caching options: `EnableHeadersHashing` vs `CleanableHashingRegexes`

### PR DESCRIPTION
**Pull request by Taiizor**
#### Hashing Behavior Configuration

- **If `EnableContentHashing` is set to `False` and `EnableHeadersHashing` is set to `False`:**
  - The output is written to Redis and remains consistent until its expiration time, even if the parameters change.
  - Hint: `CleanableHashingRegexes` is it doesnt make a difference.

- **If `EnableContentHashing` is set to `True` and `EnableHeadersHashing` is set to `False`:**
  - The output is written to Redis, but no data is ever retrieved from Redis.
  - Hint: `CleanableHashingRegexes` is not using. If used it will work.

- **If `EnableContentHashing` is set to `True` and `EnableHeadersHashing` is set to `True`:**
  - The output is written to Redis and remains consistent until its expiration time.
  - Hint: `CleanableHashingRegexes` is using. If its not used it will not work.

#### Example Usings

```json
"FileCacheOptions": {
	"TtlSeconds": 600,
	"Region": "versatile",
	"EnableContentHashing": true,
	"EnableHeadersHashing": true,
	"Header": "AL-Caching-Control",
	"CleanableHashingRegexes": [
		"cf-ray=[a-f0-9]{16}-[A-Z]{1,3}", //CloudFlare CF-RAY
		"--[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}--|(--[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})" //GUID of Parameters
	]
}
```

| Always Caching [EnableContentHashing False - EnableHeadersHashing False] |
|-------------|
| <video src="https://github.com/user-attachments/assets/ee2753c3-23be-4452-836d-ef7c25c03d1c" controls></video> |

| Nothing Caching [EnableContentHashing True - EnableHeadersHashing False] |
|------------|
| <video src="https://github.com/user-attachments/assets/d2aa0aad-5eeb-4cb9-8444-c582eaa81a48" controls></video> |

| Working Caching [EnableContentHashing True - EnableHeadersHashing True] |
|-----------|
| <video src="https://github.com/user-attachments/assets/85e89ea1-f350-4a1e-ace0-894ff5392837" controls></video> |

### Enhancements to Caching Mechanism:

* [`src/Ocelot/Cache/DefaultCacheKeyGenerator.cs`](diffhunk://#diff-8c8d0d4048c1f66a3947bb28edaa35264e4b5ba483d0c97a579f9d9bc55a18c2L31-R67): Added support for headers hashing and cleanable hashing regexes in the cache key generation process.
* [`src/Ocelot/Configuration/CacheOptions.cs`](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R32): Introduced new properties `EnableHeadersHashing` and `CleanableHashingRegexes` to the `CacheOptions` class. [[1]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R32) [[2]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fR46-R55)
* [`src/Ocelot/Configuration/Creator/CacheOptionsCreator.cs`](diffhunk://#diff-90a1f6ace5dd0b3a7b77651019f9f9a4ccebd31aa7bb21e6a81bef5b95ca53b8R13-R16): Updated the `Create` method to include the new caching options.
* [`src/Ocelot/Configuration/File/FileCacheOptions.cs`](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14): Added new properties to `FileCacheOptions` to support the new caching options. [[1]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14) [[2]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR28-R37)

### Updates to Tests:

* [`test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs`](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38): Updated test cases to include the new caching options in `CacheOptions`. [[1]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38) [[2]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L62-R62) [[3]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L75-R75)
* [`test/Ocelot.UnitTests/Cache/OutputCacheMiddlewareTests.cs`](diffhunk://#diff-225a0528c326b98f0c737ee46cd968232eabd35b9f562ff6db6f618cca9b5d2bL109-R109): Modified the downstream route setup to include the new caching options.
* [`test/Ocelot.UnitTests/CacheManager/OutputCacheMiddlewareRealCacheTests.cs`](diffhunk://#diff-bf0da9872253719440f3926db200925c2fe8f6eede96111a5f1c91252c1cfb57L80-R80): Adjusted the downstream route setup to incorporate the new caching options.
* [`test/Ocelot.UnitTests/Configuration/DownstreamRouteExtensionsTests.cs`](diffhunk://#diff-7e8bd1a3bc9e4a72e3e0d09a858db6b3b59071f5d874e8482759e6c7edfa4d69L32-R32): Updated the `CacheOptions` initialization to include the new properties.
* [`test/Ocelot.UnitTests/Configuration/RoutesCreatorTests.cs`](diffhunk://#diff-dcfb031a322a446e2066f05b751f7301ada68a9ac0127ec5a6faf5446d8187fdL184-R184): Refined the dependencies setup to include the new caching options.

These changes collectively enhance the caching capabilities by allowing more granular control over what gets hashed and cached, improving the flexibility and efficiency of the caching mechanism.

### CODE REVIEW

**Comment by Taiizor** [comment]
This pull request introduces a new feature for flexible hashing in the caching mechanism, along with several related changes to the configuration and testing files. The most important changes include modifications to the `CacheOptions` class and its usage across various components.

### New Feature: Flexible Hashing

* [`src/Ocelot/Cache/DefaultCacheKeyGenerator.cs`](diffhunk://#diff-8c8d0d4048c1f66a3947bb28edaa35264e4b5ba483d0c97a579f9d9bc55a18c2L31-R64): Added support for flexible hashing by introducing new conditions and methods for reading headers and applying regex-based cleaning.
* [`src/Ocelot/Configuration/CacheOptions.cs`](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R34): Added new properties `EnableFlexibleHashing` and `FlexibleHashingRegexes` to the `CacheOptions` class, including their initialization in the constructor. [[1]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R34) [[2]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fR48-R57)
* [`src/Ocelot/Configuration/Creator/CacheOptionsCreator.cs`](diffhunk://#diff-90a1f6ace5dd0b3a7b77651019f9f9a4ccebd31aa7bb21e6a81bef5b95ca53b8R13-R16): Updated the `Create` method to handle the new flexible hashing options.
* [`src/Ocelot/Configuration/File/FileCacheOptions.cs`](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14): Added new properties for flexible hashing in the `FileCacheOptions` class. [[1]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14) [[2]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR28-R37)

### Testing Updates

* [`test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs`](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38): Updated test cases to include the new flexible hashing parameters in `CacheOptions`. [[1]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38) [[2]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L62-R62) [[3]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L75-R75)
* [`test/Ocelot.UnitTests/Cache/OutputCacheMiddlewareTests.cs`](diffhunk://#diff-225a0528c326b98f0c737ee46cd968232eabd35b9f562ff6db6f618cca9b5d2bL109-R109): Modified test setup to include flexible hashing options in the `CacheOptions`.
* [`test/Ocelot.UnitTests/CacheManager/OutputCacheMiddlewareRealCacheTests.cs`](diffhunk://#diff-bf0da9872253719440f3926db200925c2fe8f6eede96111a5f1c91252c1cfb57L80-R80): Updated test setup to handle flexible hashing options.
* [`test/Ocelot.UnitTests/Configuration/DownstreamRouteExtensionsTests.cs`](diffhunk://#diff-7e8bd1a3bc9e4a72e3e0d09a858db6b3b59071f5d874e8482759e6c7edfa4d69L32-R32): Adjusted test cases to include the new flexible hashing parameters.
* [`test/Ocelot.UnitTests/Configuration/RoutesCreatorTests.cs`](diffhunk://#diff-dcfb031a322a446e2066f05b751f7301ada68a9ac0127ec5a6faf5446d8187fdL184-R184): Included flexible hashing options in the test setup.

### Minor Changes

* [`samples/Basic/Startup.cs`](diffhunk://#diff-4290266427f8e061b10825bfc9466cd58b9dd2a610a4e19a55c4c992e7ac45c1R29): Commented out a redundant call to `app.UseOcelot()`.

**Comment by raman-m** [comment]
Hello, Mr. @Taiizor! I will review your proposal following the .NET 9 release, likely in mid-December.

**Comment by Taiizor** [comment]
> Hello, Mr. @Taiizor! I will review your proposal following the [.NET 9](https://github.com/ThreeMammals/Ocelot/milestone/11) release, likely in mid-December.

Alright, I’ll be waiting. Let me briefly explain the changes:

When **EnableFlexibleHashing** is enabled, it reads the extra request headers from **EnableContentHashing** and adds them to the cache key. However, the parameters in the request headers include a unique GUID, which generates a unique cache key every time. 

To prevent this, I’ve added a **FlexibleHashingRegexes** setting that removes only these GUID parameters. The default behavior of this setting is to remove these GUID parameters, but it can also be defined by the user. This is important because simply removing the GUID parameters might not be enough.

### Example Scenario
A primary example of this is situations where a proxy like **CloudFlare** is used in between. These setups add their own header parameters with each request. Therefore, **FlexibleHashingRegexes** provides a solution for these cases as well.

```json
"FileCacheOptions": {
	"TtlSeconds": 600,
	"Region": "versatile",
	"EnableContentHashing": true,
	"EnableFlexibleHashing": true,
	"Header": "XY-Caching-Control",
	"FlexibleHashingRegexes": [
		"cf-ray=[a-f0-9]{16}-[A-Z]{1,3}", //CloudFlare CF-RAY
		"--[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}--|(--[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})" //GUID of Parameters
	]
}
```

**Comment by Taiizor** [comment]
## Proposed Changes

To make the functionality more customizable, the following adjustments can be made:

1. **EnableHeaderHashing**  
   - Add an option for **EnableHeaderHashing**, similar to **EnableContentHashing**.
   - Move the header-related logic from **EnableFlexibleHashing** to **EnableHeaderHashing**.

2. **Simplify EnableFlexibleHashing**  
   - Modify **EnableFlexibleHashing** to focus solely on enabling or disabling the usage of **FlexibleHashingRegexes**.

3. **Usage of FlexibleHashingRegexes**  
   - **FlexibleHashingRegexes** should handle the removal of GUID parameters and allow users to define custom regular expressions for specific header manipulations.

### Benefits:
- This approach separates the control for content and header hashing, offering more precise configuration.
- It keeps the functionality clear and easy to control, especially for cases like proxies (e.g., CloudFlare) that introduce extra header parameters.

**Comment by Taiizor** [comment]
This pull request includes several changes to enhance the caching mechanism in the Ocelot API Gateway by adding support for headers hashing and cleanable hashing regexes. The most important changes include updates to the `CacheOptions` class, modifications to the cache key generation logic, and adjustments to the related unit tests.

Enhancements to caching mechanism:

* [`src/Ocelot/Configuration/CacheOptions.cs`](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R32): Added new properties `EnableHeadersHashing` and `CleanableHashingRegexes` to the `CacheOptions` class to support headers hashing and regex-based hash cleaning. [[1]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fL23-R32) [[2]](diffhunk://#diff-5ac81887081e04efaea66d6ebcd46471982c046f82540b2545991b092ee8513fR46-R55)
* [`src/Ocelot/Configuration/Creator/CacheOptionsCreator.cs`](diffhunk://#diff-90a1f6ace5dd0b3a7b77651019f9f9a4ccebd31aa7bb21e6a81bef5b95ca53b8R13-R16): Updated the `Create` method to include the new `EnableHeadersHashing` and `CleanableHashingRegexes` properties when creating `CacheOptions` instances.
* [`src/Ocelot/Configuration/File/FileCacheOptions.cs`](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14): Added new properties `EnableHeadersHashing` and `CleanableHashingRegexes` to the `FileCacheOptions` class to support headers hashing and regex-based hash cleaning. [[1]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR13-R14) [[2]](diffhunk://#diff-8517664207de6b5c1bd65b395e0dbb5cf6ee82b882bc099873ffd92e3aeb06abR28-R37)

Modifications to cache key generation:

* [`src/Ocelot/Cache/DefaultCacheKeyGenerator.cs`](diffhunk://#diff-8c8d0d4048c1f66a3947bb28edaa35264e4b5ba483d0c97a579f9d9bc55a18c2L31-R67): Updated the `GenerateRequestCacheKey` method to incorporate headers hashing and cleanable hashing regexes into the cache key generation process. Added helper methods `ReadHeadersAsync` and `HashingClean` to support these features.

Adjustments to unit tests:

* [`test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs`](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38): Updated test cases to include the new `EnableHeadersHashing` and `CleanableHashingRegexes` properties in `CacheOptions` instances. [[1]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L38-R38) [[2]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L62-R62) [[3]](diffhunk://#diff-3968ff69e56406b78b8dcbbdabc38f167c2880da351d42d2051df3ddead13774L75-R75)
* [`test/Ocelot.UnitTests/Cache/OutputCacheMiddlewareTests.cs`](diffhunk://#diff-225a0528c326b98f0c737ee46cd968232eabd35b9f562ff6db6f618cca9b5d2bL109-R109): Adjusted the `GivenTheDownstreamRouteIs` method to include the new properties in `CacheOptions`.
* [`test/Ocelot.UnitTests/CacheManager/OutputCacheMiddlewareRealCacheTests.cs`](diffhunk://#diff-bf0da9872253719440f3926db200925c2fe8f6eede96111a5f1c91252c1cfb57L80-R80): Updated the `GivenTheDownstreamRouteIs` method to include the new properties in `CacheOptions`.
* [`test/Ocelot.UnitTests/Configuration/DownstreamRouteExtensionsTests.cs`](diffhunk://#diff-7e8bd1a3bc9e4a72e3e0d09a858db6b3b59071f5d874e8482759e6c7edfa4d69L32-R32): Modified the constructor to include the new properties in `CacheOptions`.
* [`test/Ocelot.UnitTests/Configuration/RoutesCreatorTests.cs`](diffhunk://#diff-dcfb031a322a446e2066f05b751f7301ada68a9ac0127ec5a6faf5446d8187fdL184-R184): Updated the `GivenTheDependenciesAreSetUpCorrectly` method to include the new properties in `CacheOptions`.

**Comment by raman-m** [comment]
In [Files changed](https://github.com/ThreeMammals/Ocelot/pull/2231/files) I see a lot of "fake" changes
- [Line-Ending Gotchas aka EOL Fun](https://ocelot.readthedocs.io/en/latest/building/devprocess.html#line-ending-gotchas-aka-eol-fun)

Could you explain why your PR appears to have numerous irrelevant changes aka fictious PR changes? Which IDE are you using? Please refrain from altering the line endings. Ensure that the line endings are not changed and those lines/files are excluded from PR.

**Comment by Taiizor** [comment]
> In [Files changed](https://github.com/ThreeMammals/Ocelot/pull/2231/files) I see a lot of "fake" changes
> 
> * [Line-Ending Gotchas aka EOL Fun](https://ocelot.readthedocs.io/en/latest/building/devprocess.html#line-ending-gotchas-aka-eol-fun)
> 
> Could you explain why your PR appears to have numerous irrelevant changes aka fictious PR changes? Which IDE are you using? Please refrain from altering the line endings. Ensure that the line endings are not changed and those lines/files are excluded from PR.

Im using Visual Studio 2022 Preview, and whenever I open any file in the project to make changes, it automatically makes changes like line-ending modifications or fake line changes. Honestly, I’m not sure what’s causing this behavior.

**Comment by raman-m** [comment]
>Honestly, I’m not sure what’s causing this behavior.

I'm sure, and have written a whole docs section related to EOL.
Pull top develop commits and manually copy new changes! This is the most correct dev process.

**Pull request closed without merging**
